inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 10

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[[ Run iOS Test Suite ]]'
          call: build

  - spec: mx/MXMOB*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run iOS Test Suite ]]'
          call: build

envs:
  global:
    variables:
      APP_PLATFORM: ios

parameters:
  - SAUCELABS_IOS_FILENAME: {type: string, defaultValue: "Walmart.mx.24.10.ipa", label: "<p style=\"padding-left: 20px; color: blue;\">
  <b>(mandatory)</b><br>
  Name of the .APP or .ZIP file that was uploaded into <b>SauceLabs</b>.<br>
  i.e. walmart-23.5-30-20230213.230543-1.zip<br>
</p>"}
  - BUNDLE_ID: {type: string, defaultValue: "com.walmart.bodegaGM.qa", label: "<p style=\"padding-left: 20px; color: blue;\">
  <b>(mandatory)</b><br>
  Name of the Bundle ID or App Identifier.<br>
  Option 1: com.walmartmexico.WalmartMG<br>
  Option 2: com.walmartmexico.WalmartMG.qa<br>
  Option 3: com.walmart.bodegaGM<br>
  Option 4: com.walmart.bodegaGM.qa<br>
</p>"}
  - TC_IDS: {type: string, defaultValue: "", label: "<p style=\"padding-left: 20px; color: blue;\">
  <b>(conditioned)</b>&nbsp&nbsp&nbsp(required only when <b>OVERWRITE_TC_SELECTION=true</b>)<br>
  List of Test Cases to be executed from the selected Test Suite.<br>
  Provide the list of Test Case IDs separated by comma ( , ).<br>
  i.e. 001, 002, 007, 021<br>
</p>"}
  - EXECUTION_NAME: {type: string, defaultValue: "<pre-purchase looper execution>", label: "<p style=\"padding-left: 20px; color: blue;\">
  <b>(optional)</b><br>
  Name you want to give to the execution to easily identify it in Slack's Results Post.<br>
  This name does not affect the execution.<br>
  i.e. E2E Regression 22.05.2<br>
</p>"}
  - REMOTE_DEVICE_NAME_IOS: {type: string, defaultValue: "^(?!.iPhone\WSE).*", label: "<p style=\"padding-left: 20px; color: blue;\">
  <b>(optional)</b><br>
  Device name to use when SauceLabs perform the Test Execution.<br>
  If not provided, the R2's dependencies file will use the device configured as default.<br>
  i.e. iPhone 11 Simulator<br>
  * You can also use wildcards for real device testing.<br>
</p>"}
  - REMOTE_PLATFORM_VERSION_IOS: {type: string, defaultValue: "16.*", label: "<p style=\"padding-left: 20px; color: blue;\">
  <b>(optional)</b><br>
  Platform version of the device SauceLabs will use to perform the Test Execution.<br>
  If not provided, the R2's dependencies file will use the platform version configured as default.<br>
  i.e. 14.5<br>
  * You can also use wildcards for real device testing.<br>
</p>"}
  - STOP_JIRA_REPORTING: {type: boolean, defaultValue: "true", label: "<p style=\"padding-left: 20px; color: red;\">
  [ ! ] Do NOT change default value unless you really need to test JIRA Test Execution Reports.<br>
</p>"}
  - TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: {type: boolean, defaultValue: "true", label: "<p style=\"padding-left: 20px; color: red\">
  [ ! ] Do NOT change default value unless you really need to test Individual Test Execution Squads Report in Slack.<br>
</p>"}
  - PARALLEL_EXECUTION: {type: boolean, defaultValue: "false", label: "<p style=\"padding-left: 20px; color: blue;\">
  Flag to control whether or not to execute the Test Cases in parallel.<br>
</p>"}
  - OVERWRITE_TC_SELECTION: {type: boolean, defaultValue: "false", label: "<p style=\"padding-left: 20px; color: blue;\">
  Flag to control whether or not to execute all the Test Cases included in the selected Test Suite.<br>
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp- <b>true</b> : All the Test Cases will be executed.<br>
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp- <b>false</b> : Only the selected Test Cases will be executed.<br>
  If the value has been set to <b>false</b> be sure to provide the list of Test Cases you want to execute in the var <b>TC_IDS</b>.<br>
</p>"}
  - EXECUTION_FLAGS: {type: file, label: "<p style=\"padding-left: 20px; color: blue;\">
  <b>(optional)</b><br>
  Provide a TXT file containing the Execution Flags to be used in case you need to customize the behavior of the execution.<br>
  If not provided, the execution will use the default file <b>./mx/scripts/execution-flags/execution_flags.txt</b>.<br>
</p>"}
  - GLASS_ENV: {type: choice, choices: "production,staging", label: "<p style=\"padding-left: 20px; color: blue;\">
  Environment against which the execution will be triggered.<br>
</p>"}
  - TEST_SUITE: {type: choice, choices: "qaa-prepurchase-od-smoke,qaa-dev-phase-od-prepurchase,qaa-poc-walmart-prepurchase,qaa-poc-bodega-prepurchase,dummy", label: "<p style=\"padding-left: 20px; color: blue;\">
  Test Suite to be executed.<br>
</p>"}

