inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 10

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ UPLOAD BUILD TO SAUCELABS ]]'
          call: upload_build_to_saucelabs
      - manual:
          name: 'Default Build'
          call: default
  - spec: mx/M*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ UPLOAD BUILD TO SAUCELABS ]]'
          call: upload_build_to_saucelabs
      - manual:
          name: 'Default Build'
          call: default

parameters:
    # String URL to maven artifact repository to make a CURL and download build in LooperPro Workspace.
  - URL_DOWNLOAD_BUILD: {type: string}
    # String with app platform [android | ios].
  - PLATFORM: {type: choice, choices: "android,ios"}
    # Sring with the name of the App [walmartmx | bodega | samsmx ].
  - BANNER: {type: choice, choices: "walmartmx,bodega,samsmx"}
    # String with the Release Candidate App Version.
  - RC_VERSION: {type: string}
    # Boolean flag to update app version details in Glass Automation Repo
  - UPDATE_APP_VERSION_AUTOMATION: {type: boolean, defaultValue: "true"}

envs:
  global:
    variables:
      PREFIX_SAUCE_FILE_NAME: mxqaa-${BANNER}-latest
      BASE_PATH_TO_FILE: ./mx/app/
      LOOPER_TMP_ENV_VARS: /mnt/looper/build-tmp/env_vars.sh
      BASE_PATH_TO_APP_VERSIONS: ./mx/app-versions
      BRANCH_TO_UPGRADE_APP_VERSION: development

flows:
  default:
    - shell (name Default Flow): echo 'Default Build (SUCCESS)' && exit 0
  upload_build_to_saucelabs:
    try:
      - shell (name Download App Build): |
          sh mx/scripts/download_build_looper.sh
      - shell (name Upload Build to SauceLabs): |
          sh mx/scripts/upload_build_looper.sh
      - shell (name Update App Version in Glass Automation Repo): |
          if [ "$BANNER" != "samsmx" ] && [ $UPDATE_APP_VERSION_AUTOMATION == true ]; then
            sh mx/scripts/update-app-versions.sh
          else
            echo "[INFO-QAA]: Skipping update app build info for new version uploaded to Saucelabs, banner not supported or Flag to update version is set to false"
          fi
    catch:
      - var(TEST_RUN_STATUS = $TEST_RUN_FAILED)
      - shell: exit 1
