inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

parameters:
  - APP_BUILD_URL: {type: string, defaultValue: "", label: "The url to download the app build."}
  - SAUCE_FILE_NAME: {type: string, defaultValue: "", label: "The file name that will be used on Sauce Labs storage. Example: glass-build-1234.zip"}
  - APP_PLATFORM: {type: choice, choices: "ios,android", label: ""}
  - FILE_TYPE: {type: choice, choices: "zip,ipa,apk", label: ""}

triggers:
  - push: disabled
  - pr: disabled

  - manual:
      name: Upload Build to Sauce Labs
      call: upload_build_to_sauce_labs

flows:
  download_build:
    - shell (name Download App Build): |
        sh us/scripts/download_build_looper.sh

  upload_build:
    - shell (name Upload Build to Sauce Labs): |
        sh us/scripts/upload_build_looper.sh

  upload_build_to_sauce_labs:
    - node(label = linux, isolation = except_project, ws = exclusive):
        try:
          - call: download_build
          - call: upload_build
          - shell (name Upload Details): |
              echo "Sauce Labs Username: ${SAUCE_USERNAME}"
              echo "Sauce Labs File Location: storage:filename=${SAUCE_FILE_NAME}"
        catch:
          - shell: exit 1
