configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("pi8KBOMJtPjqYOp19N2RRstt9sgbIDXW+/JZSCaClqXx+zVa3vfkXbV22lhLD39m")}
    sauceApp: "storage:filename=us-development-latest.zip"
    postToSplunk: "false"
    appBuildBranch: development-latest
  meta:
    testTags: ""
    appBuildBranch: ""
    dependencyProfile: ""

flows:
  runTests:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/wcp/looperpro/ios-prod
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          TEST_TAGS: ${testTags}
          SAUCE_APP: ${sauceApp}
          DEPENDENCY_PROFILE: ${dependencyProfile}
          POST_TO_SPLUNK: ${postToSplunk}
          APP_BUILD_BRANCH: ${appBuildBranch}
          MAPPING_LABELS: ${mappingLabels} 

  onPr:
    - checkpoint: " CI build for PR flow "
    - log: " branch :::   ${event.branch}"
    - log: ${event.payload}
    - set:
        prBranch: ${event.payload.pull_request.head.ref}
        sha: ${event.payload.pull_request.head.sha}
        baseBranch: ${event.payload.pull_request.base.ref}
        prNumber: ${event.payload.pull_request.number}
    - log: "Pr branch: ${prBranch}, base branch: ${baseBranch}, Concord process: ${txId}"
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/wcp/looperpro/ios-prod
        commitHash: ${sha}
        processId: ${txId}
        processType: "concord"
        prNumber: ${prNumber}
        suspend: true
        call: pr
      out: looperJob
    - log: "looperJob Details :: ${looperJob.status}, url: ${looperJob.url} Log: ${looperJob.log} ${looperJob.message} ${looperJob.scmEventsLog}"

triggers:

  ## development ##

  - manual:
      name: "Development - US-iOS-English-Prod-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-us-prod
        dependencyProfile: looper-us-prod-english
        mappingLabels: us_en_ios_production

  - cron:
      spec: "10 8 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-us-prod
        dependencyProfile: looper-us-prod-english
        mappingLabels: us_en_ios_production

  - manual:
      name: "Development -  MX-iOS-Prod-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-mx-ea-prod
        dependencyProfile: looper-mx-prod
        mappingLabels: mx_ea_ios_production
        sauceApp: "storage:filename=mx-development-latest.zip"

  - cron:
      spec: "20 8 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-mx-ea-prod
        dependencyProfile: looper-mx-prod
        mappingLabels: mx_ea_ios_production
        sauceApp: "storage:filename=mx-development-latest.zip"

  - manual:
      name: "Development -  MX-MH-iOS-Prod-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-mx-mh-e2e-prod
        dependencyProfile: looper-mx-merge-hallway-prod
        mappingLabels: mx_ea_ios_prod_merge_hallways
        sauceApp: "storage:filename=mx-development-latest.zip"
  
  - cron:
      spec: "20 8 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-mx-mh-e2e-prod
        dependencyProfile: looper-mx-merge-hallway-prod
        mappingLabels: mx_ea_ios_prod_merge_hallways
        sauceApp: "storage:filename=mx-development-latest.zip"

  - manual:
      name: "Development - MX-Bodega-iOS-Prod-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-bodega-ea-prod
        dependencyProfile: looper-mx-bodega-prod
        mappingLabels: bo_ea_ios_production
        sauceApp: "storage:filename=mx-bodega-development-latest.zip"

  - cron:
      spec: "30 8 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-bodega-ea-prod
        dependencyProfile: looper-mx-bodega-prod
        mappingLabels: bo_ea_ios_production
        sauceApp: "storage:filename=mx-bodega-development-latest.zip"

  - manual:
      name: "Development - CA-iOS-English-Prod-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-prod
        dependencyProfile: looper-ca-prod-english
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-development-latest.zip"

  - cron:
      spec: "40 8 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-prod
        dependencyProfile: looper-ca-prod-english
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-development-latest.zip"

  - manual:
      name: "Development - CA-iOS-English-Prod-Expressflows-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-exp-prod
        dependencyProfile: looper-ca-prod-english
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-development-latest.zip"

  - cron:
      spec: "10 10 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-exp-prod
        dependencyProfile: looper-ca-prod-english
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-development-latest.zip"

  - manual:
      name: "Development - CA-iOS-French-Prod-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-fr-prod
        dependencyProfile: looper-ca-prod-french
        mappingLabels: ca-fr_ios_production
        sauceApp: "storage:filename=ca-development-latest.zip"

  - cron:
      spec: "20 10 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-fr-prod
        dependencyProfile: looper-ca-prod-french
        mappingLabels: ca-fr_ios_production
        sauceApp: "storage:filename=ca-development-latest.zip"

  ## release ##

  - manual:
      name: "Release - US-iOS-English-Prod-Release"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-us-prod
        dependencyProfile: looper-us-prod-english-release
        mappingLabels: us_en_ios_production
        sauceApp: "storage:filename=us-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 11 * * 2-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-us-prod
        dependencyProfile: looper-us-prod-english-release
        mappingLabels: us_en_ios_production
        sauceApp: "storage:filename=us-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release - US-iOS-English-Prod-Release-TestRail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-us-prod
        dependencyProfile: looper-us-prod-english-release
        mappingLabels: us_en_ios_production
        sauceApp: "storage:filename=us-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release -  CA-iOS-English-Prod-Release"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-prod
        dependencyProfile: looper-ca-prod-english-release
        mappingLabels:  ca_ios_production
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 11 * * 2-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-prod
        dependencyProfile: looper-ca-prod-english-release
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release -  CA-iOS-English-Prod-Expressflows-Release"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-exp-prod
        dependencyProfile: looper-ca-prod-english-release
        mappingLabels:  ca_ios_production
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "0 10 * * 2-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Prod
        testTags: p1-ca-en-exp-prod
        dependencyProfile: looper-ca-prod-english-release
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-iOS-English-Prod-Release-TestRail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_TestRail
        testTags: p1-ca-en-prod
        dependencyProfile: looper-ca-prod-english-release
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-iOS-English-Prod-Expressflows-Release-TestRail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_TestRail
        testTags: p1-ca-en-exp-prod
        dependencyProfile: looper-ca-prod-english-release
        mappingLabels: ca_ios_production
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  # pr
  - github:
      version: 2
      entryPoint: "onPr"
      conditions:
        type: "pull_request"
        status: "(opened|synchronize)"
