inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

envs:
  global:
    variables:
      MARKET: sellerCenter

  # iOS
  env_ios_development_latest:
    variables:
      APP_PLATFORM: ios
      SAUCE_FILE_NAME: sc-development-latest.zip
      FILE_TYPE: zip
      APP_BRANCH: glass-qa-intel-nightly-x86_64-sim

  # Android
  env_android_development_latest:
    variables:
      APP_PLATFORM: android
      SAUCE_FILE_NAME: sc-development-latest.apk
      FILE_TYPE: apk
      APP_BRANCH: seller-development

flows:
  download_build:
    - shell (name Download App Build): |
        sh sellerCenter/scripts/download_build_looper.sh

  upload_build:
    - shell (name Upload Build to Sauce Labs): |
        sh sellerCenter/scripts/upload_build_looper.sh

  upload_build_to_sauce_labs:
    - node(label = linux, isolation = except_project, ws = exclusive):
        try:
          - declare(APP_VERSION)
          - if: $APP_VERSION
            then:
              - shell (Using manually specified APP_VERSION):
                  echo $APP_VERSION
            else:
              - call: get_app_version
          - (name Environment dump) printenv|sort
          - call: download_build
          - call: upload_build
          - var(TEST_RUN_STATUS = $TEST_RUN_PASSED)
        catch:
          - var(TEST_RUN_STATUS = $TEST_RUN_FAILED)
          - shell: exit 1

  update_by_app_branch_ios:
    call: upload_build_to_sauce_labs(env_ios_development_latest)

  update_by_app_branch_android:
    call: upload_build_to_sauce_labs(env_android_development_latest)

parameters:
  - SAUCE_USERNAME: {type: string, defaultValue: "ce-r2", label: ""}