general:
  tags: p1-sc-prod-e2e, sc-prod-feature-build

scenarios:
  - name: Before
    before: true
    endTestOnFailure: true
    flow:

  - name: Main
    flow:
      - log: Start Main

      # Login
      - executeFunction:
          name: sc.functions.accounts.login
          params:
            - name: email
              string: sc.partner1.email
            - name: password
              string: sc.partner1.password
      
      - executeFunction:
          name: sc.functions.navigation.toTab
          params:
            - name: tab
              string: Account

      - executeFunction:
          name: sc.functions.navigation.navigateToNotificationsSettings

      - executeFunction:
          name: sc.mappings.notifications.validateSettingsDisplay
          params:
            - name: settingsTitleList
              string: Customer messages,Orders,Catalog
            - name: settingsOptionsList
              string: New and unread,New Orders,Ship date at risk,Low inventory

      - executeFunction:
          name: sc.mappings.notifications.changeNotificationsSettings
          params:
            - name: settingsTitle
              string: Orders
            - name: settingsOptions
              string: New Orders
            - name: togglePushSwitch
              string: true

      - storeIn:
          key: testStatus
          value: passed