inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

triggers:
  - push: disabled
  - pr: disabled

flows:
  default:
    - echo "Looper base for transactions iOS"
  run_tests:
    - echo "Trigger branch $TRIGGER_BRANCH"
    - if: |
        %{TRIGGER_BRANCH == 'development'}
      then:
        - echo "Executing tests using development build"
        - call: run_prod_regression_flows(SAUCE_APP = 'storage:filename=ios-arm-development-latest.zip')
      else:
        - echo "Executing tests using development build"
        - call: run_prod_regression_flows(SAUCE_APP = 'storage:filename=ios-arm-release-latest.zip')

  run_scheduled_development_tests:
    - if: |
        %{TRIGGER_BRANCH == 'development'}
      then:
        - call: run_prod_regression_flows(SAUCE_APP = 'storage:filename=ios-arm-development-latest.zip')
      else:
        - echo "Exiting as cron trigger is not from development branch"

  run_scheduled_release_tests:
    - if: |
        %{TRIGGER_BRANCH == 'us/release-latest'}
      then:
        - call: run_prod_regression_flows(SAUCE_APP = 'storage:filename=ios-arm-release-latest.zip')
      else:
        - echo "Exiting as cron trigger is not from release branch"

  run_prod_regression_flows:
    try:
      - parallel(failsafe):
          - call: build(TEST_SESSION_ID = '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}')
          - var(TEST_RUN_STATUS = $TEST_RUN_PASSED)
    catch:
      - var(TEST_RUN_STATUS = $TEST_RUN_FAILED)
      - shell: exit 1
    finally:
      - call: post_report_to_slack_channel
      - call: post_email

  post_report_to_slack_channel:
    try:
      - slack.postMessage:
          iconEmoji: ":test:"
          message: $SLACK_TEST_PLAN_MESSAGE
          channelId: $SLACK_CHANNEL
          attachments:
            - fallback: ${BUILD_URL}
              actions:
                - type: "button"
                  text: "Report URL"
                  url: $REPORT_URL
    catch:
      - shell (name Slack Test Plan Step Failed): |
          echo "Slack Test Plan Step Failed - $flowErrorMessage"