inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 10

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[[ Run Customer Bodega EA iOS Test Suite ]]'
          call: build
      - manual:
          name: 'Default Build'
          call: default

  - spec: mx/MMC*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run Customer Bodega EA iOS Test Suite ]]'
          call: build
      - manual:
          name: 'Default Build'
          call: default

envs:
  global:
    variables:
      JIRA_PROJECT_ID: MMC
      APP_PLATFORM: ios
      TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: true
      SLACK_TEST_RESULTS_CHANNEL_ID: C07V58EPW5R

rules:
  before:
    group (name 'Set Global Vars'):
      - var(JIRA_SUMMARY_PREFIX):
          shell (name JIRA_SUMMARY_PREFIX): 
            echo 'bodega-'

parameters:
  # Name of the .zip file that was uploaded into Saucelabs.
  - SAUCELABS_IOS_FILENAME: {type: string, defaultValue: "25.1-mexico-bodega-release-25.1-8-20250114.121103-1.zip"}
  # Name of the Bundle ID.
  - BUNDLE_ID: {type: string, defaultValue: "com.walmart.bodegaGM.qa"}
  # List of Test Cases to be executed from the selected Test Suite. Provide the list of Test Case IDs separated by comma ( , )
  - TC_IDS: {type: string, defaultValue: ""}
  # Name you want to give to the execution to easily identify it in Slack's Results Post. This name does not affect the execution.
  - EXECUTION_NAME: {type: string, defaultValue: "<Looper - Customer - EA Bodega iOS Execution"}
  # Device name to use when SauceLabs perform the Test Execution.
  - REMOTE_DEVICE_NAME_IOS: {type: string, defaultValue: "iPhone Instant Simulator"}
  # Platform version of the device SauceLabs will use to perform the Test Execution.
  - REMOTE_PLATFORM_VERSION_IOS: {type: string, defaultValue: "17.0"}
  # Creates a Jira report. Do NOT change default value unless you really need to test JIRA Test Execution Reports.
  - STOP_JIRA_REPORTING: {type: boolean, defaultValue: "true"}
  # Flag to control whether or not to execute the Test Cases in parallel
  - PARALLEL_EXECUTION: {type: boolean, defaultValue: "true"}
  # Flag to control whether or not to execute all the Test Cases included in the selected Test Suite.
  - OVERWRITE_TC_SELECTION: {type: boolean}
  # Provide a TXT file containing the Execution Flags to be used in case you need to customize the behavior of the execution.
  - GLASS_ENV: {type: choice, choices: "production, staging"}
  # Test Suite to be executed.
  - TEST_SUITE: {type: choice, choices: "customer-bodega-ea-smoke"}
  # Mark this variable if execution is related to EA/WCP.
  - IS_WCP_TEST_EXECUTION: {type: boolean, defaultValue: "true"}
  # Defines the needed mapping labels for WCP test executions
  - PREFIX_MAPPING_LABELS: {type: string, defaultValue: "bo_ea_ios"}

flows: 
  default:
    - shell (name Default Flow): echo 'Default Build (SUCCESS)' && exit 0