inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 10

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[[ Run Customer Walmart Android Test Suite ]]'
          call: build
      - manual:
          name: 'Default Build'
          call: default

  - spec: mx/MMC*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run Customer Walmart Android Test Suite ]]'
          call: build
      - manual:
          name: 'Default Build'
          call: default

envs:
  global:
    variables:
      JIRA_PROJECT_ID: MMC
      APP_PLATFORM: android
      TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: true
      SLACK_TEST_RESULTS_CHANNEL_ID: C07V58EPW5R

parameters:
    # Name you want to give to the execution to easily identify it in Slack's Results Post. This name does not affect the execution.
  - EXECUTION_NAME: {type: string, defaultValue: "<Looper - Customer - EA Walmart Android Execution"}
    # Creates a Jira Test Execution Report. 
  - STOP_JIRA_REPORTING: {type: boolean}
    # Flag to control whether or not to execute the Test Cases in parallel
  - PARALLEL_EXECUTION: {type: boolean, defaultValue: "true"}
    # Name of the .APK file that was uploaded into Saucelabs.
  - SAUCELABS_APK_FILENAME: {type: string, defaultValue: "mxqaa-walmartmx-latest.apk"}
    # Name of the App Package.
  - APP_PACKAGE: {type: choice, choices: "com.walmart.mg.debug,com.mx.walmart.bodega.debug"}
    # Device name to use when SauceLabs perform the Test Execution.
  - DEVICE_NAME_ANDROID: {type: string, defaultValue: "Google Pixel 6 GoogleAPI Emulator"}
    # Platform version of the device SauceLabs will use to perform the Test Execution.
  - PLATFORM_VERSION_ANDROID: {type: string, defaultValue: "14.0"}
    # Environment to run test cases
  - GLASS_ENV: {type: choice, choices: "production,staging,teflon"}
    # Test Suite to be executed.
  - TEST_SUITE: {type: choice, choices: "customer-walmart-ea-smoke, customer-dev-phase"}
    # List of Test Cases to be executed from the selected Test Suite. Provide the list of Test Case IDs separated by comma ( , )
  - TC_IDS: {type: string}
    # Flag to control whether or not to execute all the Test Cases included in the selected Test Suite.
  - OVERWRITE_TC_SELECTION: {type: boolean}
    # Mark this variable if execution is related to EA/WCP.
  - IS_WCP_TEST_EXECUTION: {type: boolean}
    # Defines the needed mapping labels for WCP test executions
  - PREFIX_MAPPING_LABELS: {type: choice, choices: "X,mx_ea_android,bo_ea_android"}

rules:
  before:
    group (name 'Set Global Vars'):
      - shell (name JOB_NAME): echo $APP_PACKAGE
      - var(JIRA_SUMMARY_PREFIX):
          if: |
            %{APP_PACKAGE =~ '.*bodega.*'}
          then:
            shell (name JIRA_SUMMARY_PREFIX): echo 'bodega-'
          else:
            shell (name JIRA_SUMMARY_PREFIX): echo 'walmart-'

flows: 
  default:
    - shell (name Default Flow): echo 'Default Build (SUCCESS)' && exit 0
  