inherit: 'job:///glass-mobile-app-automation/transactions-looper-android-base'

gitShallowDepth: 10

triggers:
  - push: disabled
  - pr: disabled

envs:
  global:
    variables:
      MARKET: us
      APP_PLATFORM: android
      SKIP_SLACK_TEST_RUN: all
      SLACK_TEST_RUN_MESSAGE: "*Branch*: ${TRIGGER_BRANCH}\n
                    *App Build*: ${SAUCE_APP}\n
                    *Build Link*: ${BUILD_URL}\n
                    *Report Link*: ${REPORT_URL}"
      EMAIL_SUBJECT: Apps Android E2E Test complete - Build ${BUILD_ID}
      EMAIL_MESSAGE: "Hi Team, \n
                       Build details can be found at: ${BUILD_URL}\n
                       Test execution report results: ${REPORT_URL}\n
                       Thanks,\n
                       Cart Team."