configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("ilDlAww1fgkYQS1J3hFX+XX12PjYyqy85/g/e9zbs9Xs7YQocS82qMoAPDZs9rVe")}
    sauceApp: "storage:filename=us-development-latest.apk"
    postToSplunk: "false"
    appBuildBranch: development-latest
  meta:
    testTags: ""
    appBuildBranch: ""
    dependencyProfile: ""

flows:
  runTests:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/wcp/looperpro/android-teflon
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          TEST_TAGS: ${testTags}
          SAUCE_APP: ${sauceApp}
          DEPENDENCY_PROFILE: ${dependencyProfile}
          POST_TO_SPLUNK: ${postToSplunk}
          APP_BUILD_BRANCH: ${appBuildBranch}
          MAPPING_LABELS: ${mappingLabels} 

triggers:

  - manual:
      name: "Development - US-Android-English-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-us-teflon
        dependencyProfile: looper-us-teflon-english
        mappingLabels: us_en_android_teflon

  - cron:
      spec: "0 7 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-us-teflon
        dependencyProfile: looper-us-teflon-english
        mappingLabels: us_en_android_teflon

  - manual:
      name: "Development -  MX-Android-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_mx
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_android_teflon
        sauceApp: "storage:filename=mx-development-latest.apk"

  - cron:
      spec: "10 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_mx
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_android_teflon
        sauceApp: "storage:filename=mx-development-latest.apk"

  - manual:
      name: "Development - MX-Bodega-Android-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_mx
        testTags: pp1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_android_teflon
        sauceApp: "storage:filename=mx-bodega-development-latest.apk"

  - cron:
      spec: "20 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_mx
        testTags: p1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_android_teflon
        sauceApp: "storage:filename=mx-bodega-development-latest.apk"

  - manual:
      name: "Development -  MX-MH-Android-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-mh-e2e-teflon
        dependencyProfile: looper-mx-merge-hallway-teflon
        mappingLabels: mx_ea_android_teflon_merge_hallways
        sauceApp: "storage:filename=mx-development-latest.apk"

  - cron:
      spec: "20 8 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-mh-e2e-teflon
        dependencyProfile: looper-mx-merge-hallway-Teflon
        mappingLabels: mx_ea_android_teflon_merge_hallways
        sauceApp: "storage:filename=mx-development-latest.apk"

  - manual:
      name: "Development - CA-Android-English-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-development-latest.apk"

  - cron:
      spec: "30 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-development-latest.apk"

  - manual:
      name: "Development - CA-Android-English-Teflon-Expressflows-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-development-latest.apk"

  - cron:
      spec: "40 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-development-latest.apk"

  - manual:
      name: "Development - CA-Android-French-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-fr-teflon
        dependencyProfile: looper-ca-teflon-french
        mappingLabels: ca-fr_android_teflon
        sauceApp: "storage:filename=ca-development-latest.apk"

  - cron:
      spec: "50 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-fr-teflon
        dependencyProfile: looper-ca-teflon-french
        mappingLabels: ca-fr_android_teflon
        sauceApp: "storage:filename=ca-development-latest.apk"

  ## release ##

  - manual:
      name: "Release - CA-Android-English-Teflon-Release" 
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "0 10 * * 2-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-release-latest.apk"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-Android-English-Teflon-Expressflows-Release"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "10 10 * * 2-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-release-latest.apk"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-Android-English-Teflon-Release-TestRail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_TestRail
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-release-latest.apk"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-Android-English-Teflon-Expressflows-Release-TestRail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_TestRail
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_android_teflon
        sauceApp: "storage:filename=ca-release-latest.apk"
        appBuildBranch: release-latest

