inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: development
    scheduling: concurrent

    triggers:
      - push:
          manualOnly: true

      # Run unified flows on Prod on Release branch build
      - manual:
          name: Merge test rail run results
          call: build(APP_BUILD_BRANCH = 'release-latest')

envs:
  global:
    variables:
      MARKET: us

flows:

  setup:
    - hygieia.publishBuild()
    - shell (name Remove node_modules): |
        rm -frv node_modules
    - shell (name npm cache clear): |
        npm cache clear --force
    - shell (name sleep 10): |
        sleep 10
    - shell (name npm install): |
        npm install

  build:
    - node(label = linux, isolation = except_project, ws = exclusive, group = '${APP_PLATFORM} - ${TEST_TAGS}'):
        try:
          - call: setup
          - shell: node ./us/scripts/merge-testrail-results.js
        catch:
          - shell: exit 1

parameters:
  - SOURCE_RUN_ID: {type: string}
  - TARGET_RUN_ID: {type: string}