inherit: 'job:///glass-mobile-app-automation/transactions-looper-android-base'

gitShallowDepth: 10

triggers:
  - push: disabled
  - pr: disabled
  - manual:
      name: bookslot-android-regression
      call: run_tests(env_bookslot_android_prod_parameters)
  - cron:
      spec: "0 14 * * 0,1,3-6"
      call: run_scheduled_development_tests(env_bookslot_android_prod_parameters)
      timezone: America/Los_Angeles
  - cron:
      spec: "0 4 * * 2"
      call: run_scheduled_release_tests(env_bookslot_android_prod_parameters)
      timezone: America/Los_Angeles
  - manual:
      name: global-intent-center-android-regression
      call: run_tests(env_global_intent_center_android_prod_parameters)
  - cron:
      spec: "0 13 * * 0,1,3-6"
      call: run_scheduled_development_tests(env_global_intent_center_android_prod_parameters)
      timezone: America/Los_Angeles
  - cron:
      spec: "0 3 * * 2"
      call: run_scheduled_release_tests(env_global_intent_center_android_prod_parameters)
      timezone: America/Los_Angeles

envs:
  global:
    variables:
      MARKET: us
      APP_PLATFORM: android
      SKIP_SLACK_TEST_RUN: all
      SLACK_TEST_RUN_MESSAGE: "*Branch*: ${TRIGGER_BRANCH}\n
                    *App Build*: ${SAUCE_APP}\n
                    *Build Link*: ${BUILD_URL}\n
                    *Report Link*: ${REPORT_URL}"
      EMAIL_SUBJECT: Apps Android E2E Test complete - Build ${BUILD_ID}
      EMAIL_MESSAGE: "Hi Team, \n
                       Build details can be found at: ${BUILD_URL}\n
                       Test execution report results: ${REPORT_URL}\n
                       Thanks,\n
                       Fulfillment Experience Team."
  env_bookslot_android_prod_parameters:
    variables:
      TEST_TAGS: prod-functional-bookslot
      DEPENDENCY_PROFILE: looper-prod-bookslot
      SLACK_CHANNEL: bookslot-android-r2-automation-run
      EMAIL_TO: bookslot-mobile-andr@email.wal-mart.com
      DEPENDENCY_FILE_NAME: us/functional-tests-transactions/fulfillment-experience/dependencies/android/android-default.yaml
      GLASS_ENV: production
      MAPPING_LABELS: production
      USE_TEST_REPORT: true
      THREADS: 25
  env_global_intent_center_android_prod_parameters:
    variables:
      TEST_TAGS: prod-functional-global-intent-center
      DEPENDENCY_PROFILE: looper-prod-global-intent-center
      SLACK_CHANNEL: bookslot-android-r2-automation-run
      EMAIL_TO: bookslot-mobile-andr@email.wal-mart.com
      DEPENDENCY_FILE_NAME: us/functional-tests-transactions/fulfillment-experience/dependencies/android/android-default.yaml
      GLASS_ENV: production
      MAPPING_LABELS: production
      USE_TEST_REPORT: true
      THREADS: 25