inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: mx/release-latest
    scheduling: concurrent

    triggers:
      - pr:
          scheduling: cancelRunning
      - push:
          manualOnly: true

      - manual:
          name: MX-iOS-Prod-Release
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-prod-release', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-release-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

    #   - cron:
    #       spec: H 17,22 * * 1
    #       call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-prod-release', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-release-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

      - manual:
          name: MX-Bodega-iOS-Prod-Release
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod-release', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-release-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')

    #   - cron:
    #       spec: H 17,22 * * 1
    #       call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod-release', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-release-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')

  - spec: development
    scheduling: concurrent

    triggers:
      - pr:
          scheduling: cancelRunning
      - push:
          manualOnly: true

      - manual:
          name: MX-iOS-Prod-Release-TestRail
          call: Run_Build_Prod_TestRail(DEPENDENCY_PROFILE = 'looper-mx-prod-release', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-release-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

      - cron:
          spec: H 20 * * 1
          call: Run_Build_Prod_TestRail(DEPENDENCY_PROFILE = 'looper-mx-prod-release', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-release-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

      - manual:
          name: MX-iOS-Prod-Release
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-prod-release', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-release-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

      - cron:
          spec: H 10 * * 2-7
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-prod-release', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-release-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

      - manual:
          name: MX-Bodega-iOS-Prod-Release-TestRail
          call: Run_Build_Prod_TestRail(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod-release', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-release-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')

      - cron:
          spec: H 20 * * 1
          call: Run_Build_Prod_TestRail(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod-release', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-release-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')
      
      - manual:
          name: MX-Bodega-iOS-Prod-Release
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod-release', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-release-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')

      - cron:
          spec: H 10 * * 2-7
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod-release', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-release-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')
envs:
  global:
    variables:
      SAUCE_USERNAME: wcp-apps-e2e
      SAUCE_ACCESS_KEY: ENC[rnmbZWq+9q4Y2NblUl3yKduKKFO9zq86fEbKAl0j4lm4uh5bgYho+//5ZRtDYEqx]
      POST_TO_SPLUNK: false
      POST_TO_XRAY: false
      ELK_HOST: ENC[1daRK3FgaXEjV7OCVK+66P0fcD+RYxs47xG01WmiaDCl0xeJURP612vwYH8/8BZ31h2tnp5FT1B18us0Ag4n6fjGS3DghPw4vafKEr04BII=]
      TEST_RESULTS_INDEX: testresults_apps_wcp
      POST_TO_ES: true
      MARKET: wcp
      APP_PLATFORM: ios
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: wcp/test/dependencies/ios/ios-default.yaml
      GLASS_ENV: production
  
  testRail:
    variables:
      TESTRAIL_PLAN_ID: 796364


flows:

  #Get latest app version from txt
  get_app_version:
      - var(APP_VERSION):
          - shell (name Get App Version For MX Release): head wcp/looper/mx-release/app-version/mx-release-version.txt

  # Get latest app version from saucelabs using api
  get_build_app_version:
    try:
      - var(VERSION_NAME = 'short_version')
      - var(STORAGE_NAME):
          - shell (name STORAGE_NAME): echo ${SAUCE_APP} | cut -f2 -d'='
      - var(BUILD_APP_VERSION):
          - shell (name BUILD_APP_VERSION): |
              curl -s -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" "https://api.us-west-1.saucelabs.com/v1/storage/files?per_page=1&name=${STORAGE_NAME}" | grep -o "\"${VERSION_NAME}\": \"[^\"]*\"" | cut -f4 -d'"' | cut -f1 -d"-"
    catch:
      - echo "Unable to get Sauce Labs build appVersion - $flowErrorMessage"

  Run_Build_Prod:
    - call: build
  
  Run_Build_Prod_TestRail:
    - call: build(testRail)
