inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

parameters:
  - APP_BUILD_URL: { type: string }
  - SAUCE_FILE_NAME: { type: string }
  - APP_PLATFORM: { type: string }
  - FILE_TYPE: { type: string }
  - APP_BRANCH: { type: string }
  - MARKET: { type: string }
  - APP_BUILD_BRANCH: { type: string }

triggers:
  - push: disabled
  - pr: disabled

envs:
  global:
    variables:
      SAUCE_USERNAME: wcp-apps-e2e
      SAUCE_ACCESS_KEY: ENC[rnmbZWq+9q4Y2NblUl3yKduKKFO9zq86fEbKAl0j4lm4uh5bgYho+//5ZRtDYEqx]
      TEST_PLAN_PASSED: ":white_check_mark: *Build Success*"
      TEST_PLAN_FAILED: ":x: *Build Failure*"

flows:

  get_app_version:
    - if: |
        %{MARKET == 'mx' || MARKET == 'mx-bodega'}
      then:
        - var(APP_VERSION):
            - shell (name Get App Version): head wcp/looper/mx-release/app-version/mx-release-version.txt
      else:
        - if: |
            %{APP_PLATFORM == 'android'}
          then:
            - var(APP_VERSION):
                - shell  (name Get App Version): head us/app-versions/${APP_BUILD_BRANCH}/android.txt
          else:
            - var(APP_VERSION):
                - shell  (name Get App Version): head us/app-versions/${APP_BUILD_BRANCH}/ios.txt

  download_build:
    - shell (name Download App Build): |
        sh wcp/scripts/download_build_looper.sh

  upload_build:
    - shell (name Upload Build to Sauce Labs): |
        sh wcp/scripts/upload_build_looper.sh

  upload_build_to_sauce_labs:
    - node(label = linux, isolation = except_project, ws = exclusive):
        try:
          - declare(APP_VERSION)
          - call: get_app_version
          - (name Environment dump) printenv|sort
          - call: download_build
          - call: upload_build
          - var(TEST_RUN_STATUS = $TEST_RUN_PASSED)
        catch:
          - var(TEST_RUN_STATUS = $TEST_RUN_FAILED)
          - shell: exit 1
