configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("gXBz2BGZGZC3hV+eL2LYUMo4FI9ndjNddArCvXFpbL2ZcS70s98/kk4S3KmqasNP")}
    looperFlow: upload_build_to_sauce_labs
    custom: false
    appBranch: ""
    appBuildUrl: ""
    uploadForm.appBuildBranch: "development-latest"
  meta:
    appPlatform: ""
    fileType: ""
    appBranch: ""
    sauceFileName: ""
    market: ""
    appBuildBranch: ""

forms:
  uploadForm:
  - appBuildUrl: { label: "APP_BUILD_URL", type: "string" }
  - sauceFileName: { label: "SAUCE_FILE_NAME", type: "string" }
  - appPlatform: { label: "APP_PLATFORM", type: "string", allow: ["ios", "android"], value: "ios" }
  - fileType: { label: "FILE_TYPE", type: "string", allow: ["zip", "ipa", "apk"], value: "zip" }
  - market: { label: "MARKET", type: "string", allow: ["us", "mx", "mx-bodega", "ca"], value: "us" }
  - appBuildBranch: { label: "APP_BUILD_BRANCH", type: "string", allow: ["development-latest", "release-latest"], value: "development-latest" }

flows:
  uploadBuild:
    - if: ${custom == true}
      then:
        - form: uploadForm
    - set:
        sauceFileName: ${uploadForm.sauceFileName}
        appPlatform: ${uploadForm.appPlatform}
        fileType: ${uploadForm.fileType}
        appBuildBranch: ${uploadForm.appBuildBranch}
    - log: ${allVariables()}
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/wcp/looperpro/upload-sauce-labs
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          APP_BUILD_URL: ${uploadForm.appBuildUrl}
          SAUCE_FILE_NAME: ${uploadForm.sauceFileName}
          APP_PLATFORM: ${uploadForm.appPlatform}
          FILE_TYPE: ${uploadForm.fileType}
          APP_BRANCH: ${appBranch}
          MARKET: ${uploadForm.market}
          APP_BUILD_BRANCH: ${uploadForm.appBuildBranch}

triggers:

  - manual:
      name: "Custom - Upload"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        appBranch: custom
        custom: true

  ## development ##

  # ios
  - manual:
      name: "iOS - Development - US Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: -arm64-sim
        uploadForm.market: us

  - cron:
      spec: "10 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: -arm64-sim
        uploadForm.market: us

  - manual:
      name: "iOS - Development - MX Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim
        uploadForm.market: mx

  - cron:
      spec: "0 5,13,18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim
        uploadForm.market: mx

  - manual:
      name: "iOS - Development - MX MH Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim
        uploadForm.market: mx

  - cron:
      spec: "0 5,13,18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim
        uploadForm.market: mx

  - manual:
      name: "iOS - Development - MX-Bodega Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim
        uploadForm.market: mx-bodega

  - cron:
      spec: "0 5,13,18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim
        uploadForm.market: mx-bodega

  - manual:
      name: "iOS - Development - CA Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: canada-glass-qa-nightly-arm64-sim
        uploadForm.market: ca

  - cron:
      spec: "10 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: canada-glass-qa-nightly-arm64-sim
        uploadForm.market: ca

  # android
  - manual:
      name: "Android - Development - US Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-development
        uploadForm.market: us

  - cron:
      spec: "10 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-development
        uploadForm.market: us

  - manual:
      name: "Android - Development - MX Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-development
        uploadForm.market: mx

  - cron:
      spec: "0 5,13,18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-development
        uploadForm.market: mx

  - manual:
      name: "Android - Development - MX MH Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-development
        uploadForm.market: mx

  - cron:
      spec: "0 5,13,18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-development
        uploadForm.market: mx

  - manual:
      name: "Android - Development - MX-Bodega Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-bodega-development
        uploadForm.market: mx-bodega

  - cron:
      spec: "0 5,13,18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-bodega-development
        uploadForm.market: mx-bodega

  - manual:
      name: "Android - Development - CA Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: ca-development
        uploadForm.market: ca

  - cron:
      spec: "0 5,13,18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: ca-development
        uploadForm.market: ca

  ## release ##

  # ios

  - manual:
      name: "iOS - Release - US Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: us
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "10 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: us
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "iOS - Release - CA Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: ca
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "10 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: ca
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "iOS - Release - MX Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "0 5 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "iOS - Release - MX Merge Hallways Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "0 5 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "iOS - Release - MX-Bodega Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: mx-bodega
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "0 5 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.market: mx-bodega
        uploadForm.appBuildBranch: "release-latest"

  # android
  - manual:
      name: "Android - Release - US Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-RC
        uploadForm.market: us
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "10 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: us-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-RC
        uploadForm.market: us
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "Android - Release - CA Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: ca-RC
        uploadForm.market: ca
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "10 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ca-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: ca-RC
        uploadForm.market: ca
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "Android - Release - MX Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-RC
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "0 5 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-RC
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "Android - Release - MX Merge Hallways Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-RC
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "0 5 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-merge-hallways-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-RC
        uploadForm.market: mx
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "Android - Release - MX-Bodega Upload Latest"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-bodega-RC
        uploadForm.market: mx-bodega
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "0 5 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: mx-bodega-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: mx-bodega-RC
        uploadForm.market: mx-bodega
        uploadForm.appBuildBranch: "release-latest"
