configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("ycWGkNOUJEOd0FCBRMiAJ5FdZMZML5BR5I56TslpYSCDf1GgnYDHJ9+g0ZCcexLM")}
    sauceApp: "storage:filename=us-development-latest.zip"
    postToSplunk: "false"
    appBuildBranch: development-latest
  meta:
    testTags: ""
    appBuildBranch: ""
    dependencyProfile: ""

flows:
  runTests:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/wcp/looperpro/mx-e2e-release/ios-teflon
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          TEST_TAGS: ${testTags}
          SAUCE_APP: ${sauceApp}
          DEPENDENCY_PROFILE: ${dependencyProfile}
          POST_TO_SPLUNK: ${postToSplunk}
          APP_BUILD_BRANCH: ${appBuildBranch}
          MAPPING_LABELS: ${mappingLabels} 

#release#
triggers:

  - manual:
      name: "Rekease -  MX-iOS-Teflon-Release"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_ios_teflon
        sauceApp: "storage:filename=mx-release-latest.zip"

  - cron:
      spec: "10 14 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_ios_teflon
        sauceApp: "storage:filename=mx-release-latest.zip"

  - manual:
      name: "Release -  MX-iOS-Teflon-Release-Testrail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_TestRail
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_ios_teflon
        sauceApp: "storage:filename=mx-release-latest.zip"

  - cron:
      spec: "10 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_TestRail
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_ios_teflon
        sauceApp: "storage:filename=mx-release-latest.zip"


  - manual:
      name: "Release - MX-Bodega-iOS-Release"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: pp1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_ios_teflon
        sauceApp: "storage:filename=mx-bodega-release-latest.zip"

  - cron:
      spec: "20 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_ios_teflon
        sauceApp: "storage:filename=mx-bodega-release-latest.zip"

  - manual:
      name: "Release- MX-Bodega-iOS-Release-Testrail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_TestRail
        testTags: pp1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_ios_teflon
        sauceApp: "storage:filename=mx-bodega-release-latest.zip"

  - cron:
      spec: "20 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon_TestRail
        testTags: p1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_ios_teflon
        sauceApp: "storage:filename=mx-bodega-release-latest.zip"