inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: development
    scheduling: concurrent

    triggers:
      - push:
          manualOnly: true

      # iOS
      - manual:
          name: Upload iOS [Development] Latest
          call: upload_build_to_sauce_labs(env_ios_development_latest)

      # - cron:
      #     spec: 5 0-23 * * *
      #     call: upload_build_to_sauce_labs(env_ios_development_latest)

      - manual:
          name: Upload iOS by branch and app version
          call: update_by_app_branch_ios(APP_BRANCH = 'glass-qa-intel-nightly-sim')

      # - cron:
      #     spec: 0 0-23 * * *
      #     call: update_by_app_branch_ios(APP_BRANCH = 'glass-qa-intel-nightly-sim')

      - manual:
          name: Upload [Feature branch] iOS
          call: upload_feature_build_ios

      # Android
      - manual:
          name: Upload Android [Development] Latest
          call: upload_build_to_sauce_labs(env_android_development_latest)

      # - cron:
      #     spec: 5 0-23 * * *
      #     call: upload_build_to_sauce_labs(env_android_development_latest)

      - manual:
          name: Upload Android by branch and app version
          call: update_by_app_branch_android(APP_BRANCH = 'seller-development')

      # - cron:
      #     spec: 0 0-23 * * *
      #     call: update_by_app_branch_android(APP_BRANCH = 'seller-development')

      - manual:
          name: Upload [Feature branch] android
          call: upload_feature_build_android

      - pr: disabled

envs:
  global:
    variables:
      MARKET: sellerCenter

  # iOS
  env_ios:
   variables:
     APP_PLATFORM: ios
     SAUCE_FILE_NAME: glass-${APP_BRANCH}-${APP_VERSION}.zip
     FILE_TYPE: zip

  env_ios_development_latest:
    variables:
      APP_PLATFORM: ios
      SAUCE_FILE_NAME: sc-development-latest.zip
      FILE_TYPE: zip
      APP_BRANCH: glass-qa-intel-nightly-x86_64-sim

  env_ios_feature:
    variables:
      APP_PLATFORM: ios
      SAUCE_FILE_NAME: ${SAUCE_APP_FILE_NAME}.zip
      FILE_TYPE: zip

  # Android
  env_android:
    variables:
      APP_PLATFORM: android
      SAUCE_FILE_NAME: glass-${APP_BRANCH}-${APP_VERSION}.apk
      FILE_TYPE: apk

  env_android_development_latest:
    variables:
      APP_PLATFORM: android
      SAUCE_FILE_NAME: sc-development-latest.apk
      FILE_TYPE: apk
      APP_BRANCH: seller-development

  env_android_feature:
    variables:
      APP_PLATFORM: android
      SAUCE_FILE_NAME: ${SAUCE_APP_FILE_NAME}.apk
      FILE_TYPE: apk

flows:
  download_build:
    - shell (name Download App Build): |
        sh sellerCenter/scripts/download_build_looper.sh

  upload_build:
    - shell (name Upload Build to Sauce Labs): |
        sh sellerCenter/scripts/upload_build_looper.sh

  upload_build_to_sauce_labs:
    - node(label = linux, isolation = except_project, ws = exclusive):
        try:
          # - declare(APP_BRANCH)
          - declare(APP_VERSION)
          # - call: get_app_branch
          - if: $APP_VERSION
            then:
              - shell (Using manually specified APP_VERSION):
                  echo $APP_VERSION
            else:
              - call: get_app_version
          - (name Environment dump) printenv|sort
          - call: download_build
          - call: upload_build
          - var(TEST_RUN_STATUS = $TEST_RUN_PASSED)
        catch:
          - var(TEST_RUN_STATUS = $TEST_RUN_FAILED)
          - shell: exit 1

  update_by_app_branch_ios:
    call: upload_build_to_sauce_labs(env_ios_development_latest)

  update_by_app_branch_android:
    call: upload_build_to_sauce_labs(env_android_development_latest)

  upload_feature_build_ios:
    call: upload_build_to_sauce_labs(env_ios_feature)

  upload_feature_build_android:
    call: upload_build_to_sauce_labs(env_android_feature)

#Refer https://dx.walmart.com/nextgenci/documentation/confluence/10-Build-Parameters-2324980504 to setup password parameters
parameters:
  - APP_VERSION: {type: string, defaultValue: "", label: "Optional: Upload specific app version"}
  - SAUCE_USERNAME: {type: string, defaultValue: "ce-r2", label: ""}
  - APP_BUILD_URL: {type: string, defaultValue: "", label: "Provide artifactory download link for any feature build to be uploaded into saucelabs.
e.g : https://mvn.ci.artifacts.walmart.com/artifactory/walmart-android-mvn-snapshots-local/com/walmart/android/glass/seller-feature/glass-seller-apk-debug/24.31-debug--SNAPSHOT/glass-seller-apk-debug-24.31-debug--20240826.135444-225.apk"}
  - SAUCE_APP_FILE_NAME: {type: string, defaultValue: "sc-feature-latest", label: "Default [sc-feature-latest.zip] or [sc-feature-latest.apk]. To be used only in case APP_BUILD_URL is provided"}
  - APP_PLATFORM: {type: choice, choices: "ios,android", label: ""}
  - SAUCE_ACCESS_KEY: {type: password, defaultValue: "", label: ""}

