inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 10

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[[ Run Pre-Purchase Walmart iOS Test Suite ]]'
          call: build

  - spec: mx/MMS*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run Pre-Purchase Walmart iOS Test Suite ]]'
          call: build
  
  - spec: mx/prepurchase/release*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run Pre-Purchase Walmart iOS Test Suite ]]'
          call: build

envs:
  global:
    variables:
      JIRA_PROJECT_ID: MMS
      APP_PLATFORM: ios
      TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: true
      SLACK_TEST_RESULTS_CHANNEL_ID: C063M11HW6S

rules:
  before:
    group (name 'Set Global Vars'):
      - var(JIRA_SUMMARY_PREFIX):
          shell (name JIRA_SUMMARY_PREFIX): 
            echo 'walmart-'