inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 10

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[[ Run Pre-Purchase Bodega Android Test Suite ]]'
          call: build

  - spec: mx/MMS*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run Pre-Purchase Bodega Android Test Suite ]]'
          call: build

  - spec: mx/prepurchase/release*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run Pre-Purchase Bodega Android Test Suite ]]'
          call: build
envs:
  global:
    variables:
      JIRA_PROJECT_ID: MMS
      APP_PLATFORM: android
      TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: true
      SLACK_TEST_RESULTS_CHANNEL_ID: C063M11HW6S

rules:
  before:
    group (name 'Set Global Vars'):
      - var(JIRA_SUMMARY_PREFIX):
          shell (name JIRA_SUMMARY_PREFIX): 
            echo 'bodega-'

parameters:
  - SAUCELABS_APK_FILENAME: {type: string, defaultValue: "", label: "<p style=\"padding-left: 50px; color: blue;\">
  <b>(mandatory)</b><br><br>
  Name of the APK file that was uploaded into <b>SauceLabs</b>.<br><br>
  i.e. Glass-Android-mx-v23.4-debug-RC-debug-B8.apk<br><br>
  For more information, follow this guide 👇🏼<br>
  <a href=\"https://confluence.walmart.com/display/MXGECMEX/GlassMX+-+Automation+101\" target=\"_blank\">Automation 101</a> > 
  <a href=\"https://confluence.walmart.com/pages/viewpage.action?pageId=1631071320\" target=\"_blank\">Execute Test Suites/Test Cases</a> > 
  <a href=\"https://confluence.walmart.com/pages/viewpage.action?pageId=1631071320#GlassMXAUT10102ExecuteTestSuites/TestCases-Step2:UploadApptoSauceLabs\" target=\"_blank\">Step 2: Upload App to SauceLabs</a>
  <br>
</p>"}
  - PREFIX_MAPPING_LABELS: {type: string, defaultValue: "bo_ea_android", label: "<p style=\"padding-left: 50px; color: red;\">
  [ ! ] This variable it will only apply if IS_WCP_TEST_EXECUTION is true or checkbox is selected.<br>
</p>"}
  - TC_IDS: {type: string, defaultValue: "", label: "<p style=\"padding-left: 50px; color: blue;\">
  <b>(conditioned)</b>&nbsp&nbsp&nbsp(required only when <b>OVERWRITE_TC_SELECTION=true</b>)<br><br>
  List of Test Cases to be executed from the selected Test Suite.<br>
  Provide the list of Test Case IDs separated by comma ( , ).<br><br>
  i.e. 001, 002, 007, 021<br>
</p>"}
  - EXECUTION_NAME: {type: string, defaultValue: "<Pre-Purchase looper execution>", label: "<p style=\"padding-left: 50px; color: blue;\">
  <b>(optional)</b><br><br>
  Name you want to give to the execution to easily identify it in Slack's Results Post.<br>
  This name does not affect the execution.<br><br>
  i.e. E2E Regression 22.05.2<br>
</p>"}
  - DEVICE_NAME_ANDROID: {type: string, defaultValue: "Google Pixel 6 GoogleAPI Emulator", label: "<p style=\"padding-left: 50px; color: blue;\">
  <b>(optional)</b><br><br>
  Device name to use when SauceLabs perform the Test Execution.<br>
  If not provided, the R2's dependencies file will use the device configured as default.<br><br>
  i.e. Google Pixel 3 GoogleAPI Emulator<br>
</p>"}
  - PLATFORM_VERSION_ANDROID: {type: string, defaultValue: "12.0", label: "<p style=\"padding-left: 50px; color: blue;\">
  <b>(optional)</b><br><br>
  Platform version of the device SauceLabs will use to perform the Test Execution.<br>
  If not provided, the R2's dependencies file will use the platform version configured as default.<br><br>
  i.e. 11.0<br>
</p>"}
  - IS_WCP_TEST_EXECUTION: {type: boolean, defaultValue: "false", label: "<p style=\"padding-left: 50px; color: red;\">
  [ ! ] Mark this variable if execution it is related to EA/WCP.<br>
</p>"}
  - PARALLEL_EXECUTION: {type: boolean, defaultValue: "true", label: "<p style=\"padding-left: 50px; color: blue;\">
  Flag to control whether or not to execute the Test Cases in parallel.<br>
</p>"}
  - OVERWRITE_TC_SELECTION: {type: boolean, defaultValue: "false", label: "<p style=\"padding-left: 50px; color: blue;\">
  Flag to control whether or not to execute all the Test Cases included in the selected Test Suite.<br>
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<b>true</b> - Only the selected Test Cases will be executed.<br>
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<b>false</b> - All the Test Cases will be executed.<br><br>
  If the value has been set to <b>true</b> be sure to provide the list of Test Cases you want to execute in the var <b>TC_IDS</b> 👇🏼 below.<br>
</p>"}
  - EXECUTION_FLAGS: {type: file, label: "<p style=\"padding-left: 50px; color: blue;\">
  <b>(optional)</b><br><br>
  Provide a TXT file containing the Execution Flags to be used in case you need to customize the behavior of the execution.<br><br>
  If not provided, the execution will use the default file <a href=\"https://gecgithub01.walmart.com/MobileQE/glass-automation/blob/development/mx/scripts/execution-flags/execution_flags.txt\" target=\"_blank\">./mx/scripts/execution-flags/execution_flags.txt</a>.<br>
</p>"}
  - APP_PACKAGE: {type: choice, choices: "com.mx.walmart.bodega.debug", label: "<p style=\"padding-left: 50px; color: blue;\">
  <b>(mandatory)</b> Name of the Walmart App Package.<br><br>
  Option 1: com.walmart.mg.debug<br>
  Option 2: com.mx.walmart.bodega.debug<br>
</p>"}
  - GLASS_ENV: {type: choice, choices: "production", label: "<p style=\"padding-left: 50px; color: blue;\">
  Environment against which the execution will be triggered.<br>
</p>"}
  - TEST_SUITE: {type: choice, choices: "prepurchase-od-smoke,prepurchase-bodega-ea-smoke,prepurchase-dev-phase", label: "<p style=\"padding-left: 50px; color: blue;\">
  Test Suite to be executed.<br>
</p>"}

