configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("eD93OfESZmpExuqWe0oE2kT70KzqffWuXu/DpcsgQjysSjjh6vuM4yLSoaGWKs8w")}
    sauceApp: "storage:filename=ios-arm-development-latest.zip"
    looperFlow: run_tests
    dependencyProfile: looper
    postToSplunk: "false"
    appBuildBranch: development-latest
  meta:
    testTags: ""
    appBuildBranch: ""
    dependencyProfile: ""

flows:
  runTests:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/us/e2e-tests/looperpro/ios-teflon
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          TEST_TAGS: ${testTags}
          SAUCE_APP: ${sauceApp}
          DEPENDENCY_PROFILE: ${dependencyProfile}
          POST_TO_SPLUNK: ${postToSplunk}
          APP_BUILD_BRANCH: ${appBuildBranch}

triggers:

  ## development ##
  # - manual:
  #     name: "Development - Run [p0-ecomm-teflon-e2e] iOS E2E Golden Flows-Ecomm P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-ecomm-teflon-e2e

  # - cron:
  #     spec: "0 5,15 * * 3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-ecomm-teflon-e2e

  - manual:
      name: "Test - Run [wplus-optimize-flows] Testing wplus optimized flows"
      entryPoint: runTests
      arguments:
        testTags: wplus-optimize-flows

  - manual:
      name: "Development - Run [p1-ecomm-teflon-e2e] iOS E2E Golden Flows-Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e

  - cron:
      spec: "0 5,15 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e

  - manual:
      name: "Development - Run [p2-ecomm-teflon-e2e] iOS E2E Golden Flows-Ecomm P2"
      entryPoint: runTests
      arguments:
        testTags: p2-ecomm-teflon-e2e

  - cron:
      spec: "0 8,15 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p2-ecomm-teflon-e2e

  # Unified p0, p1 & p2 ecomm flows
  - manual:
      name: "Development - Run [unified-p0-ecomm-teflon-e2e] iOS E2E Golden Flows-Ecomm P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e

  - cron:
      spec: "0 5,15 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e

  - manual:
      name: "Development - Run [unified-p1-ecomm-teflon-e2e] iOS E2E Golden Flows-Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e

  - cron:
      spec: "0 5,15 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e

  - manual:
      name: "Development - Run [unified-p2-ecomm-teflon-e2e] iOS E2E Golden Flows-Ecomm P2"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-ecomm-teflon-e2e

  - cron:
      spec: "0 8,15 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-ecomm-teflon-e2e

  - manual:
      name: "Development - Run iOS E2E Golden Flows- duplicate pre-tx in teflon"
      entryPoint: runTests
      arguments:
        testTags: dupe-pre-tx-teflon

  - cron:
      spec: "0 15 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: dupe-pre-tx-teflon

  #faultboard
  - cron:
      spec: "0 1,20 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: faultboard

  # W+ Looper job configurations
  # - manual:
  #     name: "Development - Run [p0-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e

  # - cron:
  #     spec: "0 1,20 * * 3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e

  - manual:
      name: "Development - Run [p1-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e

  - cron:
      spec: "0 1,20 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e

  - manual:
      name: "Development - Run [p2-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P2"
      entryPoint: runTests
      arguments:
        testTags: p2-wplus-teflon-e2e

  - cron:
      spec: "0 6,22 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p2-wplus-teflon-e2e

  # Unified W+ Looper job configurations
  - manual:
      name: "Development - Run [unified-p0-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e

  - cron:
      spec: "0 1,20 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e
  
  - manual:
      name: "Development - Run [unified-p1-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e

  - cron:
      spec: "0 2,21 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e

  - manual:
      name: "Development - Run [unified-p2-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P2"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-wplus-teflon-e2e

  - cron:
      spec: "0 6,22 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-wplus-teflon-e2e

  # Run Spanish E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run iOS Spanish E2E Golden Flows"
      entryPoint: runTests
      arguments:
        looperFlow: run_spanish_tests
        testTags: p1-spanish-teflon-e2e
        dependencyProfile: looper-spanish

  - cron:
      spec: "0 17 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: run_spanish_tests
        testTags: p1-spanish-teflon-e2e
        dependencyProfile: looper-spanish

  # Run Quantum E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run iOS Quantum E2E Golden Flows"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmios

  - cron:
      spec: "0 8,20 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmios

  # Run Quantum E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run iOS Quantum E2E Golden Flows New"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmios1

  - cron:
      spec: "0 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmios1

  # Run Tipping E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run iOS Tipping E2E Golden Flows"
      entryPoint: runTests
      arguments:
        testTags: Tipping

  - cron:
      spec: "0 7,21 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: Tipping

  - manual:
      name: "Development - Run [p0-fulfillment] Android E2E Golden Flows - Ecomm P0"
      entryPoint: runTests
      arguments:
        testTags: p0-fulfillment

  - cron:
      spec: "0 7,12,21 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p0-fulfillment

  ## release ##

  - manual:
      name: "Release - Run [p0-ecomm-teflon-e2e] iOS E2E Golden Flows - Ecomm P0"
      entryPoint: runTests
      arguments:
        testTags: p0-ecomm-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  # - cron:
  #     spec: "00 12 * * 1,3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-ecomm-teflon-e2e
  #       dependencyProfile: looper-release
  #       sauceApp: "storage:filename=ios-arm-release-latest.zip"
  #       appBuildBranch: release-latest

  - manual:
      name: "Release - Run [p1-ecomm-teflon-e2e] iOS E2E Golden Flows - Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  # unified p0 ecomm flows
  - manual:
      name: "Release - Run [unified-p0-ecomm-teflon-e2e] iOS E2E Golden Flows - Ecomm P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  # unified p1 ecomm flows
  - manual:
      name: "Release - Run [unified-p1-ecomm-teflon-e2e] iOS E2E Golden Flows - Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  # W+ Looper job configurations
  # - manual:
  #     name: "Release - Run [p0-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e
  #       dependencyProfile: looper-wplus-release
  #       sauceApp: "storage:filename=ios-arm-release-latest.zip"
  #       appBuildBranch: release-latest

  # - cron:
  #     spec: "00 12 * * 1,3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e
  #       dependencyProfile: looper-wplus-release
  #       sauceApp: "storage:filename=ios-arm-release-latest.zip"
  #       appBuildBranch: release-latest

  - manual:
      name: "Release - Run [p1-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  # Unified W+ Looper job configurations
  - manual:
      name: "Release - Run [unified-p0-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest
  
  - manual:
      name: "Release - Run [unified-p1-wplus-teflon-e2e] iOS E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "30 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest

# P0 fulfillment flows
  # - manual:
  #     name: "Release - Run [p0-fulfillment] iOS E2E Golden Flows - Ecomm P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-fulfillment
  #       dependencyProfile: looper-release
  #       sauceApp: "storage:filename=ios-arm-release-latest.zip"
  #       appBuildBranch: release-latest

  # - cron:
  #     spec: "0 23 * * *"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-fulfillment
  #       dependencyProfile: looper
  #       sauceApp: "storage:filename=ios-arm-release-latest.zip"
  #       appBuildBranch: release-latest

# P0/P1 Marketplace flows
  - manual:
      name: "Run Marketplace iOS Teflon Flows"
      entryPoint: runTests
      arguments:
        testTags: unified-teflon-e2e-mp
        dependencyProfile: looper-release
        sauceApp: "storage:filename=ios-arm-release-latest.zip"
        appBuildBranch: release-latest