configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("alUUR7uSAfK2Vbq/d2t2Qq7LGNiMAVM/3YMooljRY/qi7xCJFZ6BX4+D02UAKVjt")}
    sauceApp: "storage:filename=glass-development-latest.apk"
    looperFlow: run_tests
    dependencyProfile: looper
    postToSplunk: "false"
    appBuildBranch: development-latest
  meta:
    testTags: ""
    appBuildBranch: ""
    dependencyProfile: ""

flows:
  runTests:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/us/e2e-tests/looperpro/data-creation-teflon
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          TEST_TAGS: ${testTags}
          SAUCE_APP: ${sauceApp}
          DEPENDENCY_PROFILE: ${dependencyProfile}
          POST_TO_SPLUNK: ${postToSplunk}
          APP_BUILD_BRANCH: ${appBuildBranch}

triggers:

  ## development ##
  
  - manual:
      name: "Run returns generate orders - Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: us-order-creation

  - cron:
      spec: "30 */1 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: us-order-creation

  - manual:
        name: "Run item creation script"
        entryPoint: runTests
        arguments:
          testTags: us-order-creation
          looperFlow: run_create_items

  - cron:
      spec: "30 22 * * 1"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: us-order-creation
        looperFlow: run_create_items

  - manual:
        name: "Run fetch item flows"
        entryPoint: runTests
        arguments:
          testTags: fetchItem
