inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 10

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[[ Run Purchase Bodega iOS Test Suite ]]'
          call: build

  - spec: mx/MMP*
    triggers:
      - push: disabled
      - pr: disabled
      - manual:
          name: '[!] [[ Run Purchase Bodega iOS Test Suite ]]'
          call: build

envs:
  global:
    variables:
      JIRA_PROJECT_ID: MMP
      APP_PLATFORM: ios
      TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: true
      SLACK_TEST_RESULTS_CHANNEL_ID: C07D7GXL856

parameters:
  # Name you want to give to the execution to easily identify it in Slack's Results Post. This name does not affect the execution.
  - EXECUTION_NAME: {type: string, defaultValue: "<Purchase on-demand looper execution>"}
    # Creates a Jira report. Do NOT change default value unless you really need to test JIRA Test Execution Reports.
  - STOP_JIRA_REPORTING: { type: boolean, defaultValue: "true" }
    # Name of the .zip file that was uploaded into Saucelabs.
  - SAUCELABS_IOS_FILENAME: {type: string, defaultValue: "mxqaa-bodega-latest.zip"}
    # Boolean flag to control if saucelabs ios build simulator is arm64 or x86_64
  - SAUCELABS_ARM_REQUIRED: {type: boolean}
    # Name of the Bundle ID.
  - BUNDLE_ID: {type: string, defaultValue: "com.walmart.bodegaGM.qa"}
    # Provide a TXT file containing the Execution Flags to be used in case you need to customize the behavior of the execution.
  - GLASS_ENV: {type: choice, choices: "production,staging,teflon"}
    # Test Suite to be executed.
  - TEST_SUITE: {type: choice, choices: "purchase-bodega-ea-sanity"}
    # Flag to control whether or not to execute the Test Cases in parallel
  - PARALLEL_EXECUTION: {type: boolean, defaultValue: "true"}
    # Flag to control whether or not to execute all the Test Cases included in the selected Test Suite.
  - OVERWRITE_TC_SELECTION: {type: boolean}
    # List of Test Cases to be executed from the selected Test Suite. Provide the list of Test Case IDs separated by comma ( , )
  - TC_IDS: {type: string}
    # Device name to use when SauceLabs perform the Test Execution.
  - DEVICE_NAME_IOS: {type: string, defaultValue: "iPhone Instant Simulator"}
    # Platform version of the device SauceLabs will use to perform the Test Execution.
  - PLATFORM_VERSION_IOS: {type: string, defaultValue: "latest"}
    # Mark this variable if execution is related to EA/WCP.
  - IS_WCP_TEST_EXECUTION: {type: boolean, defaultValue: "true"}
    # Defines the needed mapping labels for WCP test executions
  - PREFIX_MAPPING_LABELS: {type: choice, choices: "bo_ea_ios"}

rules:
  before:
    group (name 'Set Global Vars'):
      - shell (name IS IOS ARM ARCHITECTURE): echo $SAUCELABS_ARM_REQUIRED
      - var(APPIUM_VERSION):
          if: |
            %{SAUCELABS_ARM_REQUIRED == true}
          then:
            shell (name APPIUM_VERSION): echo '2.1.3'