inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: us/release-latest
    scheduling: concurrent

    triggers:
      - push:
          manualOnly: true

      # iOS
      - manual:
          name: Upload US iOS Release Latest
          call: upload_build_to_sauce_labs(env_us_ios_release_latest)
      
      - cron:
          spec: 10 0-23 * * *
          call: upload_build_to_sauce_labs(env_us_ios_release_latest)

      - manual:
          name: Upload CA iOS Release Latest
          call: upload_build_to_sauce_labs(env_ca_ios_release_latest)
      
      - cron:
          spec: 10 0-23 * * *
          call: upload_build_to_sauce_labs(env_ca_ios_release_latest)

      # Android
      - manual:
          name: Upload US Android Release Latest
          call: upload_build_to_sauce_labs(env_us_android_release_latest)
      
      - cron:
          spec: 10 0-23 * * *
          call: upload_build_to_sauce_labs(env_us_android_release_latest)
      
      - manual:
          name: Upload CA Android Release Latest
          call: upload_build_to_sauce_labs(env_ca_android_release_latest)

      - cron:
          spec: 10 0-23 * * *
          call: upload_build_to_sauce_labs(env_ca_android_release_latest)

      - pr: disabled


envs:
  global:
    variables:
      SAUCE_USERNAME: wcp-apps-e2e
      SAUCE_ACCESS_KEY: ENC[rnmbZWq+9q4Y2NblUl3yKduKKFO9zq86fEbKAl0j4lm4uh5bgYho+//5ZRtDYEqx]
      TEST_PLAN_PASSED: ":white_check_mark: *Build Success*"
      TEST_PLAN_FAILED: ":x: *Build Failure*"

  #iOS
  env_us_ios_release_latest:
    variables:
      MARKET: us
      APP_PLATFORM: ios
      SAUCE_FILE_NAME: us-release-latest.zip
      APP_BRANCH: glass-release-candidate-arm64-sim

  env_ca_ios_release_latest:
    variables:
      MARKET: ca
      APP_PLATFORM: ios
      SAUCE_FILE_NAME: ca-release-latest.zip
      APP_BRANCH: glass-release-candidate-arm64-sim

  #Android
  env_us_android_release_latest:
    variables:
      MARKET: us
      APP_PLATFORM: android
      SAUCE_FILE_NAME: us-release-latest.apk
      APP_BRANCH: us-RC
    
  env_ca_android_release_latest:
    variables:
      MARKET: ca
      APP_PLATFORM: android
      SAUCE_FILE_NAME: ca-release-latest.apk
      APP_BRANCH: ca-RC

flows:

  get_app_version:
    - if: |
        %{APP_PLATFORM == 'android'}
      then:
        - var(APP_VERSION):
            - shell  (name Get App Version): head us/app-versions/android.txt
      else:
        - var(APP_VERSION):
            - shell  (name Get App Version): head us/app-versions/ios.txt

  download_build:
    - shell (name Download App Build): |
        sh wcp/scripts/download_build_looper.sh

  upload_build:
    - shell (name Upload Build to Sauce Labs): |
        sh wcp/scripts/upload_build_looper.sh

  upload_build_to_sauce_labs:
    - node(label = linux, isolation = except_project, ws = exclusive):
        try:
          - declare(APP_VERSION)
          - call: get_app_version
          - (name Environment dump) printenv|sort
          - call: download_build
          - call: upload_build
          - var(TEST_RUN_STATUS = $TEST_RUN_PASSED)
        catch:
          - var(TEST_RUN_STATUS = $TEST_RUN_FAILED)
          - shell: exit 1
