inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: development
    scheduling: concurrent

    triggers:
      - pr:
          scheduling: cancelRunning
          requiredLabels:
            - "wcp-mx-ea"
            - "wcp-mx-bo"
      - push:
          manualOnly: true

      - manual:
          name: US-iOS-English-Prod-Development
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-us-prod-english', MAPPING_LABELS = 'us_en_ios_production', SAUCE_APP = 'storage:filename=us-development-latest.zip', TEST_TAGS = 'p1-us-prod')
    
      - cron:
          spec: H 8 * * *
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-us-prod-english', MAPPING_LABELS = 'us_en_ios_production', SAUCE_APP = 'storage:filename=us-development-latest.zip', TEST_TAGS = 'p1-us-prod')

      - manual:
          name: MX-iOS-Prod-Development
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-prod', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-development-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

      - cron:
          spec: H 8 * * *
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-prod', MAPPING_LABELS = 'mx_ea_ios_production', SAUCE_APP = 'storage:filename=mx-development-latest.zip', TEST_TAGS = 'p1-mx-ea-prod')

      - manual:
          name: MX-Bodega-iOS-Prod-Development
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-development-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')

      - cron:
          spec: H 8 * * * 
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-mx-bodega-prod', MAPPING_LABELS = 'bo_ea_ios_production', SAUCE_APP = 'storage:filename=mx-bodega-development-latest.zip', TEST_TAGS = 'p1-bodega-ea-prod')

      - manual:
          name: CA-iOS-English-Prod-Development
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-development-latest.zip', TEST_TAGS = 'p1-ca-en-prod')
      
      - cron:
          spec: H 8 * * *
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-development-latest.zip', TEST_TAGS = 'p1-ca-en-prod')

      - manual:
          name: CA-iOS-English-Prod-Expressflows-Development
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-development-latest.zip', TEST_TAGS = 'p1-ca-en-exp-prod')
      
      - cron:
          spec: H 10 * * *
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-development-latest.zip', TEST_TAGS = 'p1-ca-en-exp-prod')

      - manual:
          name: CA-iOS-French-Prod-Development
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-french', MAPPING_LABELS = 'ca-fr_ios_production', SAUCE_APP = 'storage:filename=ca-development-latest.zip', TEST_TAGS = 'p1-ca-fr-prod')

      - cron:
          spec: H 8 * * *
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-development-latest.zip', TEST_TAGS = 'p1-ca-fr-prod')

  - spec: us/release-latest
    scheduling: concurrent

    triggers:
      - pr:
          scheduling: cancelRunning
      - push:
          manualOnly: true

      - manual:
          name: US-iOS-English-Prod-Release
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-us-prod-english-release', MAPPING_LABELS = 'us_en_ios_production', SAUCE_APP = 'storage:filename=us-release-latest.zip', TEST_TAGS = 'p1-us-prod')
    
      - cron:
          spec: 30 11 * * 2-7
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-us-prod-english-release', MAPPING_LABELS = 'us_en_ios_production', SAUCE_APP = 'storage:filename=us-release-latest.zip', TEST_TAGS = 'p1-us-prod')

      - manual:
          name: US-iOS-English-Prod-Release-TestRail
          call: Run_Build_TestRail(DEPENDENCY_PROFILE = 'looper-us-prod-english-release', MAPPING_LABELS = 'us_en_ios_production', SAUCE_APP = 'storage:filename=us-release-latest.zip', TEST_TAGS = 'p1-us-prod')

      - manual:
          name: CA-iOS-English-Prod-Release
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english-release', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-release-latest.zip', TEST_TAGS = 'p1-ca-en-prod')

      - cron:
          spec: 30 11 * * 2-7
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english-release', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-release-latest.zip', TEST_TAGS = 'p1-ca-en-prod')

      - manual:
          name: CA-iOS-English-Prod-Expressflows-Release
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english-release', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-release-latest.zip', TEST_TAGS = 'p1-ca-en-exp-prod')

      - cron:
          spec: H 10 * * 2-7
          call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-english-release', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-release-latest.zip', TEST_TAGS = 'p1-ca-en-exp-prod')

      - manual:
          name: CA-iOS-English-Prod-Release-TestRail
          call: Run_Build_TestRail(DEPENDENCY_PROFILE = 'looper-ca-prod-english-release', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-release-latest.zip', TEST_TAGS = 'p1-ca-en-prod')

      - manual:
          name: CA-iOS-English-Prod-Expressflows-Release-TestRail
          call: Run_Build_TestRail(DEPENDENCY_PROFILE = 'looper-ca-prod-english-release', MAPPING_LABELS = 'ca_ios_production', SAUCE_APP = 'storage:filename=ca-release-latest.zip', TEST_TAGS = 'p1-ca-en-exp-prod')
    
    #   - manual:
    #       name: CA-iOS-French-Prod-Release
    #       call: Run_Build_Prod(DEPENDENCY_PROFILE = 'looper-ca-prod-french', MAPPING_LABELS = 'ca-fr_ios_production', SAUCE_APP = 'storage:filename=ca-release-latest.zip')
  
envs:
  global:
    variables:
      SAUCE_USERNAME: wcp-apps-e2e
      SAUCE_ACCESS_KEY: ENC[rnmbZWq+9q4Y2NblUl3yKduKKFO9zq86fEbKAl0j4lm4uh5bgYho+//5ZRtDYEqx]
      POST_TO_SPLUNK: false
      POST_TO_XRAY: false
      ELK_HOST: ENC[1daRK3FgaXEjV7OCVK+66P0fcD+RYxs47xG01WmiaDCl0xeJURP612vwYH8/8BZ31h2tnp5FT1B18us0Ag4n6fjGS3DghPw4vafKEr04BII=]
      TEST_RESULTS_INDEX: testresults_apps_wcp
      POST_TO_ES: true
      MARKET: wcp
      APP_PLATFORM: ios
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: wcp/test/dependencies/ios/ios-default.yaml
      GLASS_ENV: production
  
  iOS_testRail:
    variables:
      TESTRAIL_PLAN_ID: 783785

flows:

  #Get latest app version from txt
  get_app_version:
      - var(APP_VERSION):
          - shell  (name Get App Version): head us/app-versions/ios.txt


  # Get latest app version from saucelabs using api
  get_build_app_version:
    try:
      - var(VERSION_NAME = 'short_version')
      - var(STORAGE_NAME):
          - shell (name STORAGE_NAME): echo ${SAUCE_APP} | cut -f2 -d'='
      - var(BUILD_APP_VERSION):
          - shell (name BUILD_APP_VERSION): |
              curl -s -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" "https://api.us-west-1.saucelabs.com/v1/storage/files?per_page=1&name=${STORAGE_NAME}" | grep -o "\"${VERSION_NAME}\": \"[^\"]*\"" | cut -f4 -d'"' | cut -f1 -d"-"
    catch:
      - echo "Unable to get Sauce Labs build appVersion - $flowErrorMessage"

  pr:
    - parallel(failsafe):
      - call: Run_Build_Prod(TEST_TAGS = 'wcp-mx-ea-example', SAUCE_APP = 'storage:filename=mx-development-latest.zip', DEPENDENCY_PROFILE = 'looper-mx-prod', MAPPING_LABELS = 'mx_ea_ios_production')
      - call: Run_Build_Prod(TEST_TAGS = 'wcp-mx-bo-example', SAUCE_APP = 'storage:filename=mx-bodega-development-latest.zip', DEPENDENCY_PROFILE = 'looper-mx-bodega-prod', MAPPING_LABELS= 'bo_ea_ios_production')


  Run_Build_Prod:
    - call: build

  Run_Build_TestRail:
    - call: build(iOS_testRail)

