general:
  tags: unified-prod-e2e , C2659241
  inherit:
    filesRunAll:
      - us-errors-helpers.yaml
  testCaseId: C2659241
  metadata:
    - name: scenarioId
      string: 136, EC058

scenarios:
  - name: Before
    before: true
    endTestOnFailure: true
    flow:

      #Get Environment Values
      - executeFunction:
          name: us.function.utils.getEnvironmentValue

      # Set Platfrom Values
      - executeFunction:
          name: functions.utils.setPlatformInfo
                        
      # * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      - log: 'R2_SUBFLOW_PRE_TRANSACTION'
        # * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

  - name: Main
    flow:
      - log: Start main

      # Navigate onboarding to home
      - executeFunction:
          name: unified.us.functions.global.onboarding.navigateOnboardingToHome
        # Navigate to sign in page
      - executeFunction:
          name: unified.us.functions.home.navigateHomeToSignIn

      # Accoount info
      - executeFunction:
          name: unified.us.functions.authentication.signInInfo
          params:
            - name: android.email
              string: us.data.android.nonConfig.email
            - name: android.password
              string: us.data.android.nonConfig.password
            - name: ios.email
              string: us.data.ios.cart.recommendation.email
            - name: ios.password
              string: us.data.ios.cart.recommendation.password

      # Sign in with default account
      - executeFunction:
          name: unified.us.functions.global.authentication.signInAccount
          params:
            - name: email
              string: ${email}
            - name: password
              string: ${password}

      - executeFunction:
          name: unified.us.functions.global.navigation.accountToHome

        # Navigate to cart
      - executeFunction:
          name: unified.us.functions.global.navigation.toCartFromNavBar

      - executeFunction:
          name: unified.us.functions.cart.removeAllCartItems

      - executeFunction:
          name: unified.us.functions.cart.removeUnavailableItemsFromCart

      - executeFunction:
          name: unified.us.functions.global.navigation.backNavigation

      - executeFunction:
          name: unified.us.functions.search.searchItem
          params:
            - name: searchTerm
              string: 15925861 # 1471357387  #770437919, 1974251200

      - executeFunction:
          name: unified.us.functions.search.clickOnFirstItem

      - executeFunction:
          name: unified.us.functions.item.addItemToCart

      - executeFunction:
          name: unified.us.functions.gic.changeFulfillment
          params:
            - name: option
              string: Shipping

      - executeFunction:
          name: unified.us.functions.search.nonConfigBundleItem
          params:
            - name: nonConfigBundleItem
              string: nonConfigBundleItemArray

      - executeFunction: 
          name: unified.us.functions.item.verifyNonConfigItem.bundleDetails

      - executeFunction:
          name: unified.us.functions.item.addItemToCart

# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      - log: 'R2_SUBFLOW_TRANSACTION'
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

      - executeFunction:
          name: unified.us.functions.global.navigation.toCartFromNavBar

      # Verify cart page
      - executeFunction:
          name: unified.us.functions.cart.verifyNonConfigBundleViewDetails

      # Verify shipping header on review order page
      - executeFunction:
          name: unified.us.functions.verifyCardDetailsNew
          params:
            - name: cart
              string: true
            - name: listOfExpectedFulfilment
              string: Shipping

      - executeFunction:
          name: unified.us.functions.cart.editAddress
      #Recommended with your Order
      - executeFunction:
          name: unified.us.functions.cart.recommendedWithYourOrderModule
  
      - executeFunction:
          name: unified.us.functions.cart.continueToCheckout

      # Verify shipping header on review order page
      - executeFunction:
          name: unified.us.functions.verifyCardDetailsNew
          params:
            - name: reviewOrder
              string: true
            - name: listOfExpectedFulfilment
              string: Shipping

      # Verify address in review order page 
      - executeFunction:
          name: unified.us.functions.checkout.reviewOrder.verifyAddress
          params:
            - name: streetAddress
              string: 1694 Adrian Way, San Jose, CA 95122

      # Edit delivery instructions on review order screen 
      - executeFunction:  
          name: unified.us.functions.reviewOrder.editDeliveryInstructions
          params:      
            - name: accessCode
              string: 19
            - name: deliveryNotes
              string: Adding notes to delivery preferences

      - storeIn:
          key: testStatus
          value: passed

  - name: After
    after: true
    flow:
      - executeFunction:
          name: unified.us.functions.utils.afterSteps