general:
  tags: sc-e2e, sc-staging-feature-build

scenarios:
  - name: Before
    before: true
    flow:
      - if:
          condition: ${APP_PLATFORM} == 'android'
          then:
            - storeIn:
                key: identifierTextAttribute
                value: text
          else:
            - storeIn:
                key: identifierTextAttribute
                value: label

  - name: Main
    flow:
      - log: Start Main

      # Login
      - executeFunction:
          name: sc.functions.accounts.login
          params:
            - name: email
              string: sc.partner1.email
            - name: password
              string: sc.partner1.password

      - loop:
          each: "[\"sc.tab.catalog.name\", \"sc.tab.returns.name\", \"sc.tab.orders.name\", \"sc.tab.payments.name\", \"sc.tab.account.name\", \"sc.tab.wfsShipments.name\", \"sc.tab.wfsInventory.name\"]"
          storeIndex: i
          storeElement: x
          flow:

            - executeFunction:
                name: sc.functions.navigation.toTab
                params:
                  - name: tab
                    string: ${x}

            - executeFunction:
                name: sc.functions.misc.select.mpLearnIngress

            - executeFunction:
                name: sc.functions.misc.validate.learnIngressPageOpened

      - storeIn:
          key: testStatus
          value: passed
