inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 50

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled

      - cron:
          spec: "0 0 * * *"
          timezone: America/Mexico_City
          call: build

      - manual:
          name: '[[ Run Walmart EA Sanity iOS Test Suite ]]'
          call: build

  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      
      - manual:
          name: '[!] [[ Run Walmart EA Sanity iOS Test Suite ]]'
          call: build

envs:
  global:
    variables:
      APP_NAME: walmart
      APP_PLATFORM: ios
      SAUCELABS_IOS_FILENAME: ''
      SAUCELABS_IOS_VERSION: ''
      SAUCELABS_IOS_BUILD_NUMBER: ''
      BUNDLE_ID: com.walmartmexico.WalmartMG.qa
      GLASS_ENV: production
      TEST_SUITE: purchase-walmart-ea-sanity
      IS_WCP_TEST_EXECUTION: true
      PREFIX_MAPPING_LABELS: mx_ea_ios
      JIRA_PROJECT_ID: MMP
      PARALLEL_EXECUTION: true
      OVERWRITE_TC_SELECTION: false
      TC_IDS: ''
      EXECUTION_NAME: ''
      DEVICE_NAME_IOS: 'iPhone 15 Simulator'
      PLATFORM_VERSION_IOS: '17.0'
      STOP_JIRA_REPORTING: false
      TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: true
      SLACK_TEST_RESULTS_CHANNEL_ID: C07D7GXL856

rules:
  before:
    group (name 'Set Global Vars'):
      - exposeVars(./mx/app-versions/${APP_PLATFORM}/${APP_NAME}.properties)
      - var(SAUCELABS_IOS_FILENAME): ${sauceFilename}
      - var(SAUCELABS_IOS_VERSION): ${appVersion}
      - var(SAUCELABS_IOS_BUILD_NUMBER): ${buildNumber}
      - var(SAUCELABS_ARM_REQUIRED): ${isArmArchitecture}
      - shell (name IS IOS ARM ARCHITECTURE): echo $SAUCELABS_ARM_REQUIRED
      - var(APPIUM_VERSION):
          if: |
            %{SAUCELABS_ARM_REQUIRED == true}
          then:
            shell (name APPIUM_VERSION): echo '2.1.3'
      - var(EXECUTION_NAME):
          shell (name EXECUTION_NAME):
            echo 'Nightly Run - ${TEST_SUITE}-${GLASS_ENV}-${APP_NAME}-${APP_PLATFORM} - v${SAUCELABS_IOS_VERSION} (${SAUCELABS_IOS_BUILD_NUMBER})'
      - var(JIRA_SUMMARY_PREFIX):
          shell (name JIRA_SUMMARY_PREFIX): 
            echo 'nightly-'