inherit: 'job:///glass-mobile-app-automation/mx/qaa/base-job/global-base:mx/looper-configs/qaa/base/.looper-base.yml'

gitShallowDepth: 50

branches:
  - spec: development
    triggers:
      - push: disabled
      - pr: disabled

      - cron:
          spec: "0 0 * * *"
          timezone: America/Mexico_City
          call: build

      - manual:
          name: '[[ Run Walmart EA Sanity Android Test Suite ]]'
          call: build

  - spec: development
    triggers:
      - push: disabled
      - pr: disabled
      
      - manual:
          name: '[!] [[ Run Walmart EA Sanity Android Test Suite ]]'
          call: build

envs:
  global:
    variables:
      APP_NAME: walmart
      APP_PLATFORM: android
      SAUCELABS_APK_FILENAME: ''
      SAUCELABS_APK_VERSION: ''
      SAUCELABS_APK_BUILD_NUMBER: ''
      APP_PACKAGE: com.walmart.mg.debug
      GLASS_ENV: production
      TEST_SUITE: purchase-walmart-ea-sanity
      IS_WCP_TEST_EXECUTION: true
      PREFIX_MAPPING_LABELS: mx_ea_android
      JIRA_PROJECT_ID: MMP
      PARALLEL_EXECUTION: true
      OVERWRITE_TC_SELECTION: false
      TC_IDS: ''
      EXECUTION_NAME: ''
      DEVICE_NAME_ANDROID: 'Google Pixel 6 GoogleAPI Emulator'
      PLATFORM_VERSION_ANDROID: 14.0
      STOP_JIRA_REPORTING: false
      TURN_OFF_INDIVIDUAL_TEST_EXECUTION_SQUADS_REPORT: true
      SLACK_TEST_RESULTS_CHANNEL_ID: C07D7GXL856

rules:
  before:
    group (name 'Set Global Vars'):
      - exposeVars(./mx/app-versions/${APP_PLATFORM}/${APP_NAME}.properties)
      - var(SAUCELABS_APK_FILENAME): ${sauceFilename}
      - var(SAUCELABS_APK_VERSION): ${appVersion}
      - var(SAUCELABS_APK_BUILD_NUMBER): ${buildNumber}
      - var(EXECUTION_NAME):
          shell (name EXECUTION_NAME):
            echo 'Nightly Run - ${TEST_SUITE}-${GLASS_ENV}-${APP_NAME}-${APP_PLATFORM} - v${SAUCELABS_APK_VERSION}(${SAUCELABS_APK_BUILD_NUMBER})'
      - var(JIRA_SUMMARY_PREFIX):
          shell (name JIRA_SUMMARY_PREFIX): 
            echo 'nightly-'