inherit: 'job:///glass-mobile-app-automation/transactions-looper-ios-base'

gitShallowDepth: 10

triggers:
  - push: disabled
  - pr: disabled
  - manual:
      name: bookslot-ios-regression
      call: run_tests(env_bookslot_ios_prod_parameters)
  - cron:
      spec: "30 14 * * 0,1,3-6"
      call: run_scheduled_development_tests(env_bookslot_ios_prod_parameters)
      timezone: America/Los_Angeles
  - cron:
      spec: "30 4 * * 2"
      call: run_scheduled_release_tests(env_bookslot_ios_prod_parameters)
      timezone: America/Los_Angeles

envs:
  global:
    variables:
      MARKET: us
      APP_PLATFORM: ios
      SKIP_SLACK_TEST_RUN: all
      SLACK_TEST_RUN_MESSAGE: "*Branch*: ${TRIGGER_BRANCH}\n
                    *App Build*: ${SAUCE_APP}\n
                    *Build Link*: ${BUILD_URL}\n
                    *Report Link*: ${REPORT_URL}"
      EMAIL_SUBJECT: Apps iOS E2E Test complete - Build ${BUILD_ID}
      EMAIL_MESSAGE: "Hi Team, \n
                       Build details can be found at: ${BUILD_URL}\n
                       Test execution report results: ${REPORT_URL}\n
                       Thanks,\n
                       Fulfillment Experience Team."
  env_bookslot_ios_prod_parameters:
    variables:
      TEST_TAGS: prod-functional-bookslot
      DEPENDENCY_PROFILE: looper-prod-bookslot
      SLACK_CHANNEL: bookslot-ios-r2-automation-run
      EMAIL_TO: bookslot-mobile-iOS@email.wal-mart.com
      DEPENDENCY_FILE_NAME: us/functional-tests-transactions/fulfillment-experience/dependencies/ios/ios-default.yaml
      GLASS_ENV: production
      MAPPING_LABELS: production
      USE_TEST_REPORT: true
      THREADS: 25