configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("2+JM+cYVmD2Wx2iXihkkeVR1kBwzyA9NHOVWt4P4OFV5l6dLG8b9WPaPVP7/KF6N")}
    sauceApp: "storage:filename=us-development-latest.zip"
    postToSplunk: "false"
    appBuildBranch: development-latest
  meta:
    testTags: ""
    appBuildBranch: ""
    dependencyProfile: ""

flows:
  runTests:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/wcp/looperpro/ios-teflon
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          TEST_TAGS: ${testTags}
          SAUCE_APP: ${sauceApp}
          DEPENDENCY_PROFILE: ${dependencyProfile}
          POST_TO_SPLUNK: ${postToSplunk}
          APP_BUILD_BRANCH: ${appBuildBranch}
          MAPPING_LABELS: ${mappingLabels} 

#development#
triggers:

  - manual:
      name: "Development - US-iOS-English-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-us-teflon
        dependencyProfile: looper-us-teflon-english
        mappingLabels: us_en_ios_teflon

  - cron:
      spec: "0 7 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-us-teflon
        dependencyProfile: looper-us-teflon-english
        mappingLabels: us_en_ios_teflon

  - manual:
      name: "Development -  MX-iOS-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_ios_teflon
        sauceApp: "storage:filename=mx-development-latest.zip"

  - cron:
      spec: "10 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-ea-teflon
        dependencyProfile: looper-mx-teflon
        mappingLabels: mx_ea_ios_teflon
        sauceApp: "storage:filename=mx-development-latest.zip"


  - manual:
      name: "Development -  MX-MH-iOS-Prod-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-mh-e2e-teflon
        dependencyProfile: looper-mx-merge-hallway-teflon
        mappingLabels: mx_ea_ios_teflon_merge_hallways
        sauceApp: "storage:filename=mx-development-latest.zip"
  
  - cron:
      spec: "20 8 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-mx-mh-e2e-teflon
        dependencyProfile: looper-mx-merge-hallway-teflon
        mappingLabels: mx_ea_ios_teflon_merge_hallways
        sauceApp: "storage:filename=mx-development-latest.zip"

  - manual:
      name: "Development - MX-Bodega-iOS-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: pp1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_ios_teflon
        sauceApp: "storage:filename=mx-bodega-development-latest.zip"

  - cron:
      spec: "20 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-bodega-ea-teflon
        dependencyProfile: looper-mx-bodega-teflon
        mappingLabels: bo_ea_ios_teflon
        sauceApp: "storage:filename=mx-bodega-development-latest.zip"

  - manual:
      name: "Development - CA-iOS-English-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-development-latest.zip"

  - cron:
      spec: "30 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-development-latest.zip"

  - manual:
      name: "Development - CA-iOS-English-Teflon-Expressflows-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-development-latest.zip"

  - cron:
      spec: "40 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-development-latest.zip"

  - manual:
      name: "Development - CA-iOS-French-Teflon-Development"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-fr-teflon
        dependencyProfile: looper-ca-teflon-french
        mappingLabels: ca-fr_ios_teflon
        sauceApp: "storage:filename=ca-development-latest.zip"

  - cron:
      spec: "50 7,19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-fr-teflon
        dependencyProfile: looper-ca-teflon-french
        mappingLabels: ca-fr_ios_teflon
        sauceApp: "storage:filename=ca-development-latest.zip"

  ## release ##

  - manual:
      name: "Release - CA-iOS-English-Teflon-Release" 
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "0 10 * * 2-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-iOS-English-Teflon-Expressflows-Release"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - cron:
      spec: "10 10 * * 2-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_Teflon
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-iOS-English-Teflon-Release-TestRail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_TestRail
        testTags: p1-ca-en-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest

  - manual:
      name: "Release -   CA-iOS-English-Teflon-Expressflows-Release-TestRail"
      entryPoint: runTests
      arguments:
        looperFlow: Run_Build_TestRail
        testTags: p1-ca-en-exp-teflon
        dependencyProfile: looper-ca-teflon-english-release
        mappingLabels: ca_ios_teflon
        sauceApp: "storage:filename=ca-release-latest.zip"
        appBuildBranch: release-latest
