inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: development
    scheduling: concurrent

    triggers:
      - push:
          manualOnly: true

      - manual:
          name: Run Android POX Flows - Test
          call: run_android_pox_testCase(TEST_TAGS = 'ca_POX')

      - cron:
          spec: H */6 * * *
          call: run_android_pox_testCase(TEST_TAGS = 'ca_POX')

      - manual:
          name: Run ios POX Flows - Test
          call: run_ios_pox_testCase(TEST_TAGS = 'ca_POX')

      - cron:
          spec: H */6 * * *
          call: run_ios_pox_testCase(TEST_TAGS = 'ca_POX')

envs:
  global:
    variables:
      MARKET: ca
      SLACK_CHANNEL: ca-glass-pox-automation-test-result
      userName: sso-walmart-Sureshkumar.Peethambaram.Peethambaram
      accessKey: 12f59b2c-59eb-4c2c-b393-5fa03f6ac362
      POST_TO_SPLUNK: false
      POST_TO_XRAY: false

  env_android_staging:
    variables:
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: ${MARKET}/test/dependencies/android/android-default.yaml
      DEPENDENCY_PROFILE: looper-pox-android
      APP_PLATFORM: android
      GLASS_ENV: STAGING
      MAPPING_LABELS: poxstaging
      SAUCE_APP: storage:filename=${MARKET}-glassPOX.apk

  env_ios_staging:
    variables:
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: ${MARKET}/test/dependencies/ios/ios-default.yaml
      DEPENDENCY_PROFILE: looper-pox-ios
      APP_PLATFORM: ios
      GLASS_ENV: staging
      MAPPING_LABELS: poxStaging_ios
      SAUCE_APP: storage:filename=${MARKET}-glassPOX.zip

#  env_android_production:
#    variables:
#      APP_PLATFORM: android
#      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
#      DEPENDENCY_FILE_NAME: ${MARKET}/test/dependencies/android/android-default.yaml
#      DEPENDENCY_PROFILE:
#      GLASS_ENV:
#      MAPPING_LABELS:
#      SAUCE_APP: storage:filename=${MARKET}-walmart-development-latest.apk
#
#  env_ios_production:
#    variables:
#      APP_PLATFORM: ios
#      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
#      DEPENDENCY_FILE_NAME: ${MARKET}/test/dependencies/ios/ios-default.yaml
#      DEPENDENCY_PROFILE:
#      GLASS_ENV:
#      MAPPING_LABELS:
#      SAUCE_APP: storage:filename=${MARKET}-walmart-development-latest.zip

flows:

#  run_android_pox_testCase:
#    - call: build(env_android_production)
#  run_ios_pox_testCase:
#    - call: build(env_ios_production)
  run_android_pox_testCase:
    - call: build(env_android_staging)

  run_ios_pox_testCase:
    - call: build(env_ios_staging)
