inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

parameters:
  - TEST_TAGS: { type: string }
  - SAUCE_APP: { type: string }
  - DEPENDENCY_PROFILE: { type: string }
  - POST_TO_SPLUNK: { type: string }
  - APP_BUILD_BRANCH: { type: string }
  - MAPPING_LABELS: { type: string }

envs:
  global:
    variables:
      SAUCE_USERNAME: wcp-apps-e2e
      SAUCE_ACCESS_KEY: ENC[rnmbZWq+9q4Y2NblUl3yKduKKFO9zq86fEbKAl0j4lm4uh5bgYho+//5ZRtDYEqx]
      POST_TO_SPLUNK: false
      POST_TO_XRAY: false
      ELK_HOST: ENC[1daRK3FgaXEjV7OCVK+66P0fcD+RYxs47xG01WmiaDCl0xeJURP612vwYH8/8BZ31h2tnp5FT1B18us0Ag4n6fjGS3DghPw4vafKEr04BII=]
      TEST_RESULTS_INDEX: testresults_apps_wcp
      POST_TO_ES: true
      MARKET: wcp
      APP_PLATFORM: android
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: wcp/test/dependencies/android/android-default.yaml
      GLASS_ENV: production


  android_testRail:
    variables:
      TESTRAIL_PLAN_ID: 792550

flows:

  # Get latest app version from txt
  get_app_version:
      - var(APP_VERSION):
        - shell  (name Get App Version): head wcp/looper/mx-release/app-version/mx-release-version.txt
  

  # Get latest app version from saucelabs using api
  get_build_app_version:
    try:
      - var(VERSION_NAME = 'version')
      - var(STORAGE_NAME):
          - shell (name STORAGE_NAME): echo ${SAUCE_APP} | cut -f2 -d'='
      - var(BUILD_APP_VERSION):
          - shell (name BUILD_APP_VERSION): |
              curl -s -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" "https://api.us-west-1.saucelabs.com/v1/storage/files?per_page=1&name=${STORAGE_NAME}" | grep -o "\"${VERSION_NAME}\": \"[^\"]*\"" | cut -f4 -d'"' | cut -f1 -d"-"
    catch:
      - echo "Unable to get Sauce Labs build appVersion - $flowErrorMessage"
      
  pr:
    - parallel(failsafe):
      - call: Run_Build_Prod(TEST_TAGS = 'wcp-mx-ea-example', SAUCE_APP = 'storage:filename=mx-development-latest.apk', DEPENDENCY_PROFILE = 'looper-mx-prod', MAPPING_LABELS = 'mx_ea_android_production')
      - call: Run_Build_Prod(TEST_TAGS = 'wcp-mx-bo-example', SAUCE_APP = 'storage:filename=mx-bodega-development-latest.apk', DEPENDENCY_PROFILE = 'looper-mx-bodega-prod', MAPPING_LABELS= 'bo_ea_android_production')



  Run_Build_Prod:
    - call: build

  Run_Build_TestRail:
    - call: build(android_testRail)
