inherit: 'job:///carta-jobs/apps/looper-base:.looper-carta.yml'

gitShallowDepth: 10

branches:
  - spec: development
    scheduling: concurrent

    triggers:
      - pr: disabled
      - push:
          manualOnly: true

      - manual:
          name: E2E Android Tests
          call: e2e_test

envs:
  global:
    variables:
      MARKET: us
      SLACK_CHANNEL: r2-glass-test-result
      POST_TO_ES: false
      POST_TO_ANIVIA: false
      APPLITOOLS_API_KEY: ENC[Rt+/oXg4fNf9b2Pq2MQ47frfGB42KVDp7l7/tQ/1na985VV7Ia42QMgDDOppIoaDTWfXJmsQW0Imo7rpXjXaQQ==]
      SAUCE_APP: 'storage:filename=glass-release-latest.apk'
      APP_BUILD_BRANCH: 'release-latest'
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: us/e2e-tests/dependencies/android/android-default.yaml
      APP_PLATFORM: android
      PLATFORM_TYPE: Android

  # Environment profiles can be specified here with specific environment variable values.
  env_android_teflon:
    variables:
      GLASS_ENV: teflon
      TEST_ENV: Teflon
      DEPENDENCY_PROFILE: 'carta-looper-teflon'

  env_android_production:
    variables:
      GLASS_ENV: production
      TEST_ENV: Production
      DEPENDENCY_PROFILE: 'carta-looper-prod'

flows:
  e2e_test:
    - switch($ENV):
        case('teflon'):
          - echo "Environment Teflon"
          - call: build_carta(env_android_teflon)
        case('production'):
          - echo "Environment Production"
          - call: build_carta(env_android_production)
        otherwise:
          - echo "No Environment Passed"

  build_carta:
    - ? node(label = linux, isolation = except_project, ws = exclusive, group = '${APP_PLATFORM} - ${TEST_TAGS}')
      : try:
          - declare(APP_VERSION)
          - call: setup
          - call: get_app_version
          - call: get_repository_build
          - call: return_sauce_app_location
          - call: get_build_app_version
          - call: execute_test
          - call: generate_sauce_labs_build_url
          - call: publish_report
          - call: get_test_failures
          - var(TEST_RUN_STATUS = $TEST_RUN_PASSED)
        catch:
          - var(TEST_RUN_STATUS = $TEST_RUN_FAILED)
          - shell: exit 1
        finally:
          - call: generate_email_template
