inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

triggers:
  - pr: disabled
  - push: disabled

  - manual:
      name: test-sm-ios
      call: build_sm_ios

  - manual:
      name: test-sm-android
      call: build_sm_android

envs:
  global:
    variables:
      MARKET: us
      DATA_FILE: ./smdata.json
      TEST_RESULTS_FILE: ./smresults.json
      # SLACK_CHANNEL: r2-glass-test-result
      START_TIME: ""
      END_TIME: ""
      POST_TO_ES: true
      REPORT_PATH: http://cdc-obj-torbit-103.storage.cloud.wal-mart.com/swift/v1/looper-electrode/reports/${JOB_NAME}/${BUILD_ID}/screenshots
      GLASS_ENV: production
      MAPPING_LABELS: production-sm
      TEST_TAGS: site-merchandising
      DEPENDENCY_PROFILE: sm-prod

  env_ios_sm:
    variables:
      APP_PLATFORM: ios
      DEPENDENCY_FILE_NAME: us/e2e-tests/dependencies/ios/ios-default.yaml
      SAUCE_APP: storage:filename=ios-arm-release-latest.zip
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      EMAIL_SUBJECT: Apps iOS E2E Site Merch Test Complete - Build ${BUILD_ID}
      EMAIL_MESSAGE:
        "Test Results:
        http://grafana.teflon.walmartlabs.com/d/_ORtCX84k/glass-e2e-apps-site-merch?orgId=1&from=now-7d&to=now&var-buildId=${BUILD_ID}&var-platform=${APP_PLATFORM}"

  env_android_sm:
    variables:
      APP_PLATFORM: android
      DEPENDENCY_FILE_NAME: us/e2e-tests/dependencies/android/android-default.yaml
      SAUCE_APP: storage:filename=glass-release-latest.apk
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      EMAIL_SUBJECT: Apps Android E2E Site Merch Test Complete - Build ${BUILD_ID}
      EMAIL_MESSAGE:
        "Test Results:
        http://grafana.teflon.walmartlabs.com/d/_ORtCX84k/glass-e2e-apps-site-merch?orgId=1&from=now-7d&to=now&var-buildId=${BUILD_ID}&var-platform=${APP_PLATFORM}"

flows:
  setup:
    - hygieia.publishBuild()
    - shell (name Remove node_modules): |
        rm -frv node_modules
    - shell (name npm cache clear): |
        npm cache clear --force
    - shell (name sleep 10): |
        sleep 10
    - shell (name npm install): |
        npm install
    - if: |
        %{USE_CUSTOM_R2_JAR == 'false'}
      then:
        - shell (name download r2 binary): |
            npm run download-r2
      else:
        - shell: echo Using custom R2 jar

  publish_screenshots:
    - var(reportExists): if [ -d "report" ]; then echo "true"; fi;
    - shell(name $reportExists): echo $reportExists
    - if: $reportExists
      then:
        - try:
            - shell(silent):
                (cd ./report/images && tree -H . > index.html)
            - publishReport:
                context: screenshots
                dir: "./report/images"
                index: index.html
                verbose: true
          catch:
            - echo "Publish Report step failed - $flowErrorMessage"

  build_sm:
    - node(label = linux, isolation = except_project, ws = exclusive, group = '${APP_PLATFORM} - ${TEST_TAGS}'):
        try:
          - declare(APP_VERSION)
          - call: setup
          # - call: get_app_version
          # - call: get_repository_build
          # - call: return_sauce_app_location
          # - call: get_build_app_version
          - shell (name Print All ENV): |
              printenv|sort
          - shell: echo ${SM_JSON} > smdata.json
          - shell: cat smdata.json
          - shell: node ./us/e2e-tests/helpers/generate-campaign-tests.js
          - var(START_TIME):
              - shell(silent): date +"%Y-%m-%dT%H:%M:%S%z"
          - call: execute_test
          - var(END_TIME):
              - shell(silent): date +"%Y-%m-%dT%H:%M:%S%z"
          - call: generate_sauce_labs_build_url
          - call: publish_report
          - call: publish_screenshots
          # - shell: node ./us/scripts/generateSMSummaryReport.js
          - shell: node ./us/scripts/generateDigitalEyesReportForAstro.js
        finally:
          - call: post_email(email)

  build_sm_ios:
    - call: build_sm(env_ios_sm)

  build_sm_android:
    - call: build_sm(env_android_sm)
