inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: development
    scheduling: concurrent

    triggers:
      - pr: disabled
      - push:
          manualOnly: true

     
      - manual:
          name: Run returns generate orders - Ecomm P1
          call: run_tests(SAUCE_APP = 'storage:filename=glass-development-latest.apk', APP_BUILD_BRANCH = 'development-latest', TEST_TAGS = 'us-order-creation', DEPENDENCY_PROFILE = 'looper')

      - cron:
          spec: "30 */1 * * *"
          call: run_tests(SAUCE_APP = 'storage:filename=glass-development-latest.apk', APP_BUILD_BRANCH = 'development-latest', TEST_TAGS = 'us-order-creation', DEPENDENCY_PROFILE = 'looper')
   
   
envs:
  global:
    variables:
      MARKET: us
      APP_PLATFORM: android
      SLACK_CHANNEL: r2-glass-test-result
      POST_TO_ES: true
      POST_TO_ANIVIA: true
      APPLITOOLS_API_KEY: ENC[Rt+/oXg4fNf9b2Pq2MQ47frfGB42KVDp7l7/tQ/1na985VV7Ia42QMgDDOppIoaDTWfXJmsQW0Imo7rpXjXaQQ==]

  # Environment profiles can be specified here with specific environment variable values.
  env_android_teflon:
    variables:
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: us/e2e-tests/dependencies/android/android-default.yaml
    #   DEPENDENCY_PROFILE: looper
      GLASS_ENV: teflon
      MAPPING_LABELS: teflon

flows:
  run_tests:
    - call: build(env_android_teflon)
