configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("DC1BUOqFS7G0RGePqfasAxWs2yg79WgzcLemRiTbiyw7oqmv+jmJIUcIb5lfmlIw")}
    looperFlow: upload_build_to_sauce_labs
    custom: false
    appBranch: ""
    appBuildUrl: ""
    uploadForm.appBuildBranch: "development-latest"
  meta:
    appPlatform: ""
    fileType: ""
    appBranch: ""
    sauceFileName: ""
    appBuildBranch: ""

forms:
  uploadForm:
  - appBuildUrl: { label: "APP_BUILD_URL", type: "string" }
  - sauceFileName: { label: "SAUCE_FILE_NAME", type: "string" }
  - appPlatform: { label: "APP_PLATFORM", type: "string", allow: ["ios", "android"], value: "ios" }
  - fileType: { label: "FILE_TYPE", type: "string", allow: ["zip", "ipa", "apk"], value: "zip" }
  - appBuildBranch: { label: "APP_BUILD_BRANCH", type: "string", allow: ["development-latest", "release-latest"], value: "development-latest" }

flows:
  uploadBuild:
    - if: ${custom == true}
      then:
        - form: uploadForm
    - set:
        sauceFileName: ${uploadForm.sauceFileName}
        appPlatform: ${uploadForm.appPlatform}
        fileType: ${uploadForm.fileType}
        appBuildBranch: ${uploadForm.appBuildBranch}
    - log: ${allVariables()}
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/us/upload-sauce-labs
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          APP_BUILD_URL: ${uploadForm.appBuildUrl}
          SAUCE_FILE_NAME: ${uploadForm.sauceFileName}
          APP_PLATFORM: ${uploadForm.appPlatform}
          FILE_TYPE: ${uploadForm.fileType}
          APP_BRANCH: ${appBranch}
          APP_BUILD_BRANCH: ${uploadForm.appBuildBranch}

triggers:

  - manual:
      name: "Custom - Upload"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        appBranch: custom
        custom: true

  ## development ##

  # ios
  - manual:
      name: "Development - Upload Latest iOS (Intel)"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim

  - cron:
      spec: "5 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-qa-intel-nightly-x86_64-sim

  - manual:
      name: "Development - Upload Latest iOS (ARM)"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ios-arm-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: -arm64-sim

  - cron:
      spec: "5 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ios-arm-development-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: -arm64-sim

  # android
  - manual:
      name: "Development - Upload Latest Android"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-development

  - cron:
      spec: "5 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-development-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-development

  ## release ##

  # ios
  - manual:
      name: "Release - Upload Latest iOS (Intel)"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-x86_64-sim
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "5 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-x86_64-sim
        uploadForm.appBuildBranch: "release-latest"

  - manual:
      name: "Release - Upload Latest iOS (ARM)"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ios-arm-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "5 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: ios-arm-release-latest.zip
        uploadForm.appPlatform: ios
        uploadForm.fileType: zip
        appBranch: glass-release-candidate-arm64-sim
        uploadForm.appBuildBranch: "release-latest"

  # android
  - manual:
      name: "Release - Upload Latest Android"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-RC
        uploadForm.appBuildBranch: "release-latest"

  - cron:
      spec: "5 0-23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: uploadBuild
      arguments:
        looperFlow: upload_build_to_sauce_labs
        uploadForm.sauceFileName: glass-release-latest.apk
        uploadForm.appPlatform: android
        uploadForm.fileType: apk
        appBranch: us-RC
        uploadForm.appBuildBranch: "release-latest"
