configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("h15RGtJnbpPw1nscQ+/v1xVK2SNSq6lEBfnKZacWHWefDb9/xO+evjt6fZTlWxOk")}
    sauceApp: "storage:filename=glass-development-latest.apk"
    looperFlow: run_tests
    dependencyProfile: looper
    postToSplunk: "false"
    appBuildBranch: development-latest
  meta:
    testTags: ""
    appBuildBranch: ""
    dependencyProfile: ""

flows:
  runTests:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/us/e2e-tests/looperpro/android-teflon
        call: ${looperFlow}
        suspend: true
        sync: true
        parameters:
          TEST_TAGS: ${testTags}
          SAUCE_APP: ${sauceApp}
          DEPENDENCY_PROFILE: ${dependencyProfile}
          POST_TO_SPLUNK: ${postToSplunk}
          APP_BUILD_BRANCH: ${appBuildBranch}

triggers:

  ## development ##
  # - manual:
  #     name: "Development - Run [p0-ecomm-teflon-e2e] Android E2E Golden Flows-Ecomm P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-ecomm-teflon-e2e

  # - cron:
  #     spec: "0 5,14 * * 3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-ecomm-teflon-e2e

  - manual:
      name: "Test - Run [wplus-optimize-flows] Testing wplus optimized flows"
      entryPoint: runTests
      arguments:
        testTags: wplus-optimize-flows

  - manual:
      name: "Development - Run [p1-ecomm-teflon-e2e] Android E2E Golden Flows-Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e

  - cron:
      spec:  "0 5,14 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e

  - manual:
      name: "Development - Run [p2-ecomm-teflon-e2e] Android E2E Golden Flows-Ecomm P2"
      entryPoint: runTests
      arguments:
        testTags: p2-ecomm-teflon-e2e

  - cron:
      spec: "0 8,14 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p2-ecomm-teflon-e2e

  # Unified p0, p1 & p2 ecomm flows
  - manual:
      name: "Development - Run [unified-p0-ecomm-teflon-e2e] Android E2E Golden Flows-Ecomm P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e

  - cron:
      spec: "0 5,14 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e

  - manual:
      name: "Development - Run [unified-p1-ecomm-teflon-e2e] Android E2E Golden Flows-Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e

  - cron:
      spec: "0 5,14 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e

  - manual:
      name: "Development - Run [unified-p2-ecomm-teflon-e2e] Android E2E Golden Flows-Ecomm P2"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-ecomm-teflon-e2e

  - cron:
      spec: "0 8,14 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-ecomm-teflon-e2e

  - manual:
      name: "Development - Run Android E2E Golden Flows- duplicate pre-tx in teflon"
      entryPoint: runTests
      arguments:
        testTags: dupe-pre-tx-teflon

  - cron:
      spec: "0 14 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: dupe-pre-tx-teflon

  #faultboard
  - cron:
      spec: "0 3,19 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: faultboard

  - manual:
      name: "Development - Run Android E2E PetRx flows in teflon"
      entryPoint: runTests
      arguments:
        testTags: PetRx

  - manual:
      name: "Development - Run Android E2E Tipping flows in teflon"
      entryPoint: runTests
      arguments:
        testTags: Tipping

  # W+ Looper job configurations
  # - manual:
  #     name: "Development - Run [p0-wplus-teflon-e2e] Android E2E Wplus Golden Flows P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e

  # - cron:
  #     spec: "0 3,19 * * 3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e

  - manual:
      name: "Development - Run [p1-wplus-teflon-e2e] Android E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e

  - cron:
      spec: "0 3,19 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e

  - manual:
      name: "Development - Run [p2-wplus-teflon-e2e] Android E2E Wplus Golden Flows P2"
      entryPoint: runTests
      arguments:
        testTags: p2-wplus-teflon-e2e

  - cron:
      spec: "0 7,23 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p2-wplus-teflon-e2e

  # Unified W+ Looper job configurations
  - manual:
      name: "Development - Run [unified-p0-wplus-teflon-e2e] Android E2E Wplus Golden Flows P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e

  - cron:
      spec: "0 3,19 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e
  
  - manual:
      name: "Development - Run [unified-p1-wplus-teflon-e2e] Android E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e

  - cron:
      spec: "0 4,20 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e

  - manual:
      name: "Development - Run [unified-p2-wplus-teflon-e2e] Android E2E Wplus Golden Flows P2"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-wplus-teflon-e2e

  - cron:
      spec: "0 7,23 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p2-wplus-teflon-e2e

  - manual:
      name: "Development - Run iOS Teflon Ecomm P1 flows on Feature build- All"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e

  - manual:
      name: "Development - Run P1 W+ Teflon flows on Feature build"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e

  - manual:
      name: "Development - Run P2 W+ Teflon flows on Feature build"
      entryPoint: runTests
      arguments:
        testTags: p2-wplus-teflon-e2e


  # Run Spanish E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run Android Spanish E2E Golden Flows"
      entryPoint: runTests
      arguments:
        looperFlow: run_spanish_tests
        testTags: p1-spanish-teflon-e2e
        dependencyProfile: looper-spanish

  - cron:
      spec: "0 17 * * 3-7"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: run_spanish_tests
        testTags: p1-spanish-teflon-e2e
        dependencyProfile: looper-spanish

  # Run Quantum E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run Android Quantum E2E Golden Flows"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmandroid

  - cron:
      spec: "0 6,17 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmandroid

  # Run Quantum E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run Android Quantum E2E Golden Flows New"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmandroid1

  - cron:
      spec: "0 6,17 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        looperFlow: run_tests_quantum
        testTags: qmandroid1

  # Run Tipping E2E flows on Teflon on Dev build
  - manual:
      name: "Development - Run Android Tipping E2E Golden Flows"
      entryPoint: runTests
      arguments:
        testTags: Tipping

  - cron:
      spec: "0 7,21 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: Tipping

  # Run Fulcrum E2E flows on teflon build
  - manual:
      name: "Development - Run Android Tipping E2E Golden Flows"
      entryPoint: runTests
      arguments:
        testTags: p1-fulcrum-teflon-e2e

  - cron:
      spec: "0 7,21 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-fulcrum-teflon-e2e

  - manual:
      name: "Development - Run [p0-fulfillment] Android E2E Golden Flows - Ecomm P0"
      entryPoint: runTests
      arguments:
        testTags: p0-fulfillment

  - cron:
      spec: "0 8,10,23 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p0-fulfillment

  ## release ##

  # - manual:
  #     name: "Release - Run [p0-ecomm-teflon-e2e] Android E2E Golden Flows - Ecomm P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-ecomm-teflon-e2e
  #       dependencyProfile: looper-release
  #       sauceApp: "storage:filename=glass-release-latest.apk"
  #       appBuildBranch: release-latest

  # - cron:
  #     spec: "00 12 * * 1,3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-ecomm-teflon-e2e
  #       dependencyProfile: looper-release
  #       sauceApp: "storage:filename=glass-release-latest.apk"
  #       appBuildBranch: release-latest

  - manual:
      name: "Release - Run [p1-ecomm-teflon-e2e] Android E2E Golden Flows - Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "0 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  # unified p0 ecomm flows
  - manual:
      name: "Release - Run [unified-p0-ecomm-teflon-e2e] Android E2E Golden Flows - Ecomm P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "30 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-ecomm-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  # unified p1 ecomm flows
  - manual:
      name: "Release - Run [unified-p1-ecomm-teflon-e2e] Android E2E Golden Flows - Ecomm P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "0 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-ecomm-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  # W+ Looper job configurations
  # - manual:
  #     name: "Release - Run [p0-wplus-teflon-e2e] Android E2E Wplus Golden Flows P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e
  #       dependencyProfile: looper-wplus-release
  #       sauceApp: "storage:filename=glass-release-latest.apk"
  #       appBuildBranch: release-latest

  # - cron:
  #     spec: "00 12 * * 1,3-7"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-wplus-teflon-e2e
  #       dependencyProfile: looper-wplus-release
  #       sauceApp: "storage:filename=glass-release-latest.apk"
  #       appBuildBranch: release-latest

  - manual:
      name: "Release - Run [p1-wplus-teflon-e2e] Android E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "0 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  # Unified W+ Looper job configurations
  - manual:
      name: "Release - Run [unified-p0-wplus-teflon-e2e] Android E2E Wplus Golden Flows P0"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "0 18 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p0-wplus-teflon-e2e
        dependencyProfile: looper-release
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest
  
  - manual:
      name: "Release - Run [unified-p1-wplus-teflon-e2e] Android E2E Wplus Golden Flows P1"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest

  - cron:
      spec: "0 19 * * *"
      timezone: "America/Los_Angeles"
      entryPoint: runTests
      arguments:
        testTags: unified-p1-wplus-teflon-e2e
        dependencyProfile: looper
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest
# P0 fulfillment flows
  # - manual:
  #     name: "Release - Run [p0-fulfillment] Android E2E Golden Flows - Ecomm P0"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-fulfillment
  #       dependencyProfile: looper-release
  #       sauceApp: "storage:filename=glass-release-latest.apk"
  #       appBuildBranch: release-latest

  # - cron:
  #     spec: "0 23 * * *"
  #     timezone: "America/Los_Angeles"
  #     entryPoint: runTests
  #     arguments:
  #       testTags: p0-fulfillment
  #       dependencyProfile: looper
  #       sauceApp: "storage:filename=glass-release-latest.apk"
  #       appBuildBranch: release-latest

# P0/P1 Marketplace flows
  - manual:
      name: "Run Marketplace Android Teflon Flows"
      entryPoint: runTests
      arguments:
        testTags: unified-teflon-e2e-mp
        dependencyProfile: looper-release
        sauceApp: "storage:filename=glass-release-latest.apk"
        appBuildBranch: release-latest