inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

branches:
  - spec: development
    scheduling: concurrent

    triggers:
      - pr:
          scheduling: cancelRunning
          requiredLabels:
            - "ca"
      - push:
          manualOnly: true

      - manual:
          name: Run iOS Test - Staging
          call: run_staging(TEST_TAGS = 'fr_ca')

      - cron:
          spec: 0 */6 * * *
          call: run_staging(TEST_TAGS = 'fr_ca')

  # - spec: ca/release-latest
  #   scheduling: concurrent

  #   triggers:
  #     - pr:
  #         scheduling: cancelRunning
  #         requiredLabels:
  #           - "ca"
  #     - push:
  #         manualOnly: true

  #     - manual:
  #         name: Run iOS Example Test
  #         call: run_tests(TEST_TAGS = 'example-test')

envs:
  global:
    variables:
      MARKET: ca
      APP_PLATFORM: ios
      SLACK_CHANNEL: r2-ca-glass-test-result
      SAUCE_USERNAME: CanadaMobile
      SAUCE_ACCESS_KEY: be7b5ef5-86d1-450d-94ba-f3234f736ab8
      POST_TO_SPLUNK: false
      POST_TO_XRAY: false

  env_ios_staging:
    variables:
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: ${MARKET}/test/dependencies/ios/ios-default.yaml
      DEPENDENCY_PROFILE: fr_looper
      GLASS_ENV: staging
      MAPPING_LABELS: fr_stagingIos
      SAUCE_APP: storage:filename=${MARKET}-walmart-development-latest.zip

flows:
  pr:
    - call: run_staging(TEST_TAGS = 'fr_ca')

  run_staging:
    - call: build(env_ios_staging)
