configuration:
  runtime: "concord-v2"
  processTimeout: "PT4H"
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:looper-task:latest"
  arguments:
    username: svcstoreautomation
    baseUrl: "https://looperpro-cigateway.prod.walmart.com"
    apiToken: ${crypto.decryptString("ObWyDmhGk5nnSwT8N53S9MNFTsyR09mRLk6G9U3kvW5T0npnoPl2m0EIs0FRambG")}

flows:
  codeFreeze:
    - task: looper
      in:
        username: ${username}
        baseUrl: ${baseUrl}
        apiToken: ${apiToken}
        jobName: glass-automation/us/e2e-tests/looperpro/codefreeze
        call: ${looperFlow}
        suspend: true
        sync: true

triggers:

  - manual:
      name: Run Codefreeze Tasks
      entryPoint: codeFreeze
      arguments:
        looperFlow: release_branch_and_update_appversion
      
  - cron:
      spec: "0 10 * * 2"
      timezone: "America/Los_Angeles"
      entryPoint: codeFreeze
      arguments:
        looperFlow: release_branch_and_update_appversion

  - manual:
      name: Run Update Release Branch Only
      entryPoint: codeFreeze
      arguments:
        looperFlow: update_release_branch

