inherit: 'job:///glass-mobile-app-automation/looper-base:.looper.yml'

gitShallowDepth: 10

parameters:
  - TEST_TAGS: { type: string }
  - SAUCE_APP: { type: string }
  - DEPENDENCY_PROFILE: { type: string }
  - POST_TO_SPLUNK: { type: string }
  - APP_BUILD_BRANCH: { type: string }
  - MAPPING_LABELS: { type: string }

envs:
  global:
    variables:
      SAUCE_USERNAME: wcp-apps-e2e
      SAUCE_ACCESS_KEY: ENC[rnmbZWq+9q4Y2NblUl3yKduKKFO9zq86fEbKAl0j4lm4uh5bgYho+//5ZRtDYEqx]
      POST_TO_SPLUNK: false
      POST_TO_XRAY: false
      ELK_HOST: ENC[1daRK3FgaXEjV7OCVK+66P0fcD+RYxs47xG01WmiaDCl0xeJURP612vwYH8/8BZ31h2tnp5FT1B18us0Ag4n6fjGS3DghPw4vafKEr04BII=]
      TEST_RESULTS_INDEX: testresults_apps_wcp
      POST_TO_ES: true
      MARKET: wcp
      APP_PLATFORM: android
      TEST_SESSION_ID: '%{(Math.abs(new(java.util.Random).nextInt()) % 100000000 + 1)}'
      DEPENDENCY_FILE_NAME: wcp/test/dependencies/android/android-default.yaml

  android_testRail:
    variables:
      GLASS_ENV: teflon
      TESTRAIL_PLAN_ID: 796669

  android_teflon:
    variables:
      GLASS_ENV: teflon
  
  android_teflon_mx:
    variables:
      GLASS_ENV: production


flows:
  # Get latest app version from txt
  get_app_version:
    - var(APP_VERSION):
        - shell  (name Get App Version): head us/app-versions/${APP_BUILD_BRANCH}/android.txt


  # Get latest app version from saucelabs using api
  get_build_app_version:
    try:
      - var(VERSION_NAME = 'version')
      - var(STORAGE_NAME):
          - shell (name STORAGE_NAME): echo ${SAUCE_APP} | cut -f2 -d'='
      - var(BUILD_APP_VERSION):
          - shell (name BUILD_APP_VERSION): |
              curl -s -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" "https://api.us-west-1.saucelabs.com/v1/storage/files?per_page=1&name=${STORAGE_NAME}" | grep -o "\"${VERSION_NAME}\": \"[^\"]*\"" | cut -f4 -d'"' | cut -f1 -d"-"
    catch:
      - echo "Unable to get Sauce Labs build appVersion - $flowErrorMessage"

  Run_Build_Teflon:
    - call: build(android_teflon)
  
  Run_Build_Teflon_TestRail:
    - call: build(android_testRail)

  Run_Build_Teflon_mx:
    - call: build(android_teflon_mx)
