name: Autoheal identifiers (from app changes)

on:
  repository_dispatch:
    types: [app_change]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  autoheal:
    name: extract IDs → update mappings → PR
    runs-on: ubuntu-latest

    env:
      # Required secrets (set these in repo Settings → Secrets and variables → Actions)
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}     # repo-scoped is fine for same-repo PR
      # Optional cross-repo PAT if you dispatch from another repo
      # CROSS_REPO_PAT:  ${{ secrets.CROSS_REPO_PAT }}

    steps:
      - name: Echo dispatch payload (debug)
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "event_type=${{ github.event.action || github.event.repository_dispatch_type }}"
          echo "client_payload:"
          echo '${{ toJson(github.event.client_payload) }}'

      - name: Checkout repo at requested ref (or main)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha || github.event.client_payload.branch || 'main' }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -e .

      - name: Write config.yaml for CLI (OpenAI + RN patterns)
        run: |
          mkdir -p autoheal_fw/config
          cat > autoheal_fw/config/config.yaml <<'YAML'
          app:
            platform: react_native
            testid_to_logical: {}
            testid_patterns: []
            ios_patterns: []
            android_patterns: []

          source_files:
            react_native:
              - "src/catalog.ts"
              - "src/menu.ts"
            ios_native: []
            android_native: []

          llm:
            provider: openai
            openai_api_key: "${OPENAI_API_KEY:-}"
            anthropic_api_key: "${ANTHROPIC_API_KEY:-}"
            model: "gpt-4o"
            temperature: 0.1

          vectordb:
            provider: local
            api_key: ""
            index_name: "autoheal-failures"
            base_path: "./vector_index"

          vcs:
            provider: local
            github_token: "${GITHUB_TOKEN:-}"
            repo: "idcmurali1/Automation-test-framework-HOB"

          ci:
            provider: local

          artifact_store:
            path: "./artifacts"

          policy:
            file: "./policies/policy.yaml"

          logging:
            level: "INFO"
            patch_ledger: "./patches/ledger.jsonl"
          YAML
          echo "Wrote autoheal_fw/config/config.yaml"

      - name: Run autoheal (extract IDs → update mappings → PR)
        run: |
          source venv/bin/activate
          python -m autoheal.cli update-mappings-from-app \
            --app_repo "$GITHUB_WORKSPACE/hob-shop" \
            --tests_repo "$GITHUB_WORKSPACE" \
            --logical "" \
            --branch "autoheal/ids-$(date +%Y%m%d-%H%M%S)" \
            --config "autoheal_fw/config/config.yaml" \
            --github_token "${GITHUB_TOKEN:-}"

      - name: Upload artifacts (debug)
        uses: actions/upload-artifact@v4
        with:
          name: autoheal-artifacts
          path: |
            artifacts/**
            autoheal_fw/config/config.yaml
          if-no-files-found: ignore
