name: Autoheal: extract IDs → update mappings → PR

on:
  workflow_dispatch:
  # Optional: run when a PR changes the app or test files
  pull_request:
    paths:
      - "hob-shop/**"
      - "us/e2e-tests/**"
      - "autoheal_fw/**"
      - ".github/workflows/autoheal-identifiers.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  app_change:
    runs-on: ubuntu-24.04

    env:
      # Force OpenAI provider (no more rulebased unless you set it)
      LLM_PROVIDER: openai
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout test framework repo (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout app repo (hob-shop) to subfolder
        uses: actions/checkout@v4
        with:
          repository: idcmurali1/hob-shop
          path: hob-shop
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv & install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          if [ -f autoheal_fw/requirements.txt ]; then
            pip install --upgrade pip
            pip install -r autoheal_fw/requirements.txt
          else
            pip install --upgrade pip
            pip install pyyaml requests scikit-learn
          fi

      - name: Write config.yaml for CLI (OpenAI + RN patterns)
        run: |
          mkdir -p autoheal_fw/config
          cat > autoheal_fw/config/config.yaml <<'YAML'
          app:
            platform: react_native

            # Exact RN testID -> logical
            testid_to_logical:
              product_sku_hoodie:  us.mappings.yourOrders.hoodieProduct
              product_sku_cap:     us.mappings.yourOrders.capProduct

            # Flexible RN families (regex)
            testid_patterns:
              - match: "^product_sku_hoodie.*$"
                logical: us.mappings.yourOrders.hoodieProduct
              - match: "^product_sku_cap.*$"
                logical: us.mappings.yourOrders.capProduct
              - match: "^product_sku_shirt.*$"
                logical: us.mappings.yourOrders.shirtProduct

            # Optional native patterns
            ios_patterns:
              - match: "^(settingsButton|.*SettingsButton.*)$"
                logical: us.mappings.account.menuSettingsButton

            android_patterns:
              - match: "^com\\.walmart\\.android\\.debug:id/account_header_settings.*$"
                logical: us.mappings.account.menuSettingsButton
              - match: "^product_sku_hoodie.*$"
                logical: us.mappings.yourOrders.hoodieProduct
              - match: "^product_sku_cap.*$"
                logical: us.mappings.yourOrders.capProduct

          source_files:
            react_native:
              - "src/catalog.ts"
              - "src/menu.ts"
            ios_native:
              - "ios/Views/ProductView.swift"
              - "ios/Controllers/MenuController.swift"
            android_native:
              - "android/app/src/main/java/com/walmart/app/CatalogActivity.java"
              - "android/app/src/main/java/com/walmart/app/MenuActivity.java"

          llm:
            provider: ${LLM_PROVIDER:-openai}
            openai_api_key: "${OPENAI_API_KEY:-}"
            anthropic_api_key: "${ANTHROPIC_API_KEY:-}"
            model: "gpt-4o"
            temperature: 0.1

          vectordb:
            provider: local
            api_key: ""
            index_name: "autoheal-failures"
            base_path: "./vector_index"

          vcs:
            provider: local
            github_token: "${GITHUB_TOKEN:-}"
            repo: "idcmurali1/Automation-test-framework-HOB"

          ci:
            provider: local

          artifact_store:
            path: "./artifacts"

          policy:
            file: "./policies/policy.yaml"

          logging:
            level: "INFO"
            patch_ledger: "./patches/ledger.jsonl"
          YAML

      - name: Run autoheal (extract IDs → update mappings → PR)
        env:
          PYTHONPATH: ${{ github.workspace }}/autoheal_fw
        run: |
          source venv/bin/activate
          echo "__main__: LLM provider=${LLM_PROVIDER:-openai} model=gpt-4o"
          python -m autoheal.cli update-mappings-from-app \
            --app_repo "$GITHUB_WORKSPACE/hob-shop" \
            --tests_repo "$GITHUB_WORKSPACE" \
            --logical "" \
            --branch "autoheal/update-identifiers" \
            --config "$GITHUB_WORKSPACE/autoheal_fw/config/config.yaml" \
            --github_token "${GITHUB_TOKEN}"

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autoheal-artifacts
          path: |
            artifacts/**
            autoheal_fw/config/config.yaml
